/**
 * Special Ability Descriptions for Mythras Classic Fantasy
 * Used for auto-fill descriptions and tooltips
 */

const AbilityDescriptions = {
  "agelessness": "Maintain current age & avoid Aging penalties. Immune to magical aging.",
  "agile": "While Unburdened (ENC < STR×2) and wearing light armor or less, the character can use heightened reflexes in combat. Requires 60% or higher in Evade or Acrobatics. Add one-tenth of your Athletics skill as a bonus to your Initiative roll (1d10). For example, Athletics 60% grants +6 to Initiative.",
  "alter self": "As per spell Alter Self.",
  "amphibious": "Breathe underwater and on dry land with no difficulty.",
  "animal companion 1": "Call & befriend 1 animal companion nearby. See description.",
  "animal companion 2": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion 3": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion 4": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion 5": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion i": "Call & befriend 1 animal companion nearby. See description.",
  "animal companion ii": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion iii": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion iv": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal companion v": "Call & befriend 1 larger animal companion nearby. See description.",
  "animal empathy": "Influence v Willpower natural animals to stop violence. See description.",
  "arcane spellcaster": "You may cast Arcane spells.",
  "armor proficiency": "Reduce damage from 1 attack/Combat Round by 1 point.",
  "arrowcut": "If Extremely Unburdened & no armor, can Parry arrows, darts, & spears.",
  "artful dodger": "+10% bonus to Evade and won't go Prone.",
  "bard magical items": "Use \"Mage-only\" magic items & scrolls. See description.",
  "bard magic items": "Use \"Mage-only\" magic items & scrolls. See description.",
  "bard spellcasting": "Cast magic with Musicianship (and Sing to Augment). See description.",
  "bardic spellcasting": "Cast magic with Musicianship (and Sing to Augment). See description.",
  "bardic spellcaster": "Cast magic with Musicianship (and Sing to Augment). See description.",
  "bard spellcaster": "Cast magic with Musicianship (and Sing to Augment). See description.",
  "berserk rage": "Incredible strength & bloodlust. See description.",
  "brute strength": "1x/day, increase Brawn by 1 Difficulty Grade easier.",
  "burrower": "Tunnel through mud, sand, or dirt at normal Movement Rate, but not rock.",
  "call war horse": "War horse magically appears at your position.",
  "camouflage": "When in natural environ., Perception rolls to see you are 1 Grade more Difficult.",
  "camouflaged": "In natural environs, others suffer 2 Diff. Grade to their Perception vs your Stealth.",
  "circle of power": "If using holy weapon, hostile magic in 10' radius is suppressed. See description.",
  "cleric magical items": "Use \"Cleric-only\" magic items except books & scrolls.",
  "climb walls": "If Unburdened & wearing Light armor, ignore 1 Grade on Athletics when climbing.",
  "cold-blooded": "Only needs 1 meal/week. See description for more info.",
  "combat proficiency": "+5% to Combat Skill & Unarmed (already included).",
  "commanding": "1x/day per Rank it's 2 Grades easier to Influence or Insight.",
  "counter song": "Spend 1 Magic Point and 1 Action Point to counter sound-based magical effects. Roll Sing or Musicianship as an Opposed Roll against the source. If successful, allies within 30 feet are immune to audible enchantments (such as a siren's song or harpy's scream) for 1 minute per Rank. The effect can be maintained.",
  "cure disease": "1x/week per Rank, remove 1 natural disease.",
  "darkvision": "See up to 60' in dim light as if bright light (Standard Perc.) and darkness as if dim light (Hard Perception).",
  "defensive reflexes 1": "1 bonus Action Point for Parry or Evade.",
  "defensive reflexes 2": "2 bonus Action Points for Parry or Evade.",
  "defensive reflexes 3": "3 bonus Action Points for Parry or Evade.",
  "defensive reflexes 4": "4 bonus Action Points for Parry or Evade.",
  "defensive reflexes i": "1 bonus Action Point for Parry or Evade.",
  "defensive reflexes ii": "2 bonus Action Points for Parry or Evade.",
  "defensive reflexes iii": "3 bonus Action Points for Parry or Evade.",
  "defensive reflexes iv": "4 bonus Action Points for Parry or Evade.",
  "detect evil": "Detect Evil beings within 60' & in field of vision.",
  "detect magic and illusions": "Willpower check to sense magic auras or items.",
  "determination": "Roll against Oath. Success = ignore Serious Wounds & Fatigue.",
  "divine protection": "+10% to Willpower, Endurance, & Evade when needed.",
  "divine spellcasting": "You may cast Divine magic.",
  "diving strike": "Plummet from the sky, Charging your enemy. See the link for more information.",
  "dual weapon specialist 1": "Strike with 2 weapons simul. Attack is 1 Grade Difficult.",
  "dual weapon specialist 2": "Double Critical on attacks. Damage Mod goes up 1 step.",
  "dual weapon specialist i": "Strike with 2 weapons simul. Attack is 1 Grade Difficult.",
  "dual weapon specialist ii": "Double Critical on attacks. Damage Mod goes up 1 step.",
  "dual weapon specialist": "Strike with 2 weapons simul. Attack is 1 Grade Difficult.",
  "elven chain": "May cast Arcane magic spells while wearing elven chain at 1 Diff. Grade harder.",
  "exotic mounts 1": "May obtain unicorn as mount. See description.",
  "exotic mounts 2": "May obtain pegasus as mount. See description.",
  "exotic mounts 3": "May obtain hippogriff as mount. See description.",
  "exotic mounts 4": "May obtain griffon as mount. See description.",
  "exotic mounts i": "May obtain unicorn as mount. See description.",
  "exotic mounts ii": "May obtain pegasus as mount. See description.",
  "exotic mounts iii": "May obtain hippogriff as mount. See description.",
  "exotic mounts iv": "May obtain griffon as mount. See description.",
  "exposure tolerance": "Reduced effects from extreme temperatures based on your origin (cold, hot, etc.).",
  "extra rage 1": "1 more use of Berserk Rage/day.",
  "extra rage 2": "2 more uses of Berserk Rage/day.",
  "extra rage 3": "3 more uses of Berserk Rage/day.",
  "extra rage 4": "4 more uses of Berserk Rage/day.",
  "extra rage i": "1 more use of Berserk Rage/day.",
  "extra rage ii": "2 more uses of Berserk Rage/day.",
  "extra rage iii": "3 more uses of Berserk Rage/day.",
  "extra rage iv": "4 more uses of Berserk Rage/day.",
  "extra turning": "2x the # of times you can Turn Undead. See description.",
  "familiar": "Gain a familiar as in spell. See description.",
  "fleet of foot": "If Unburdened & wearing Light armor, Outmaneuvers are 2 Difficulty Grades Easier.",
  "flurry of blows": "Immediate follow-up attack after 1st attack.",
  "flying": "Can fly and does not need to roll Flying skill unless difficult maneuver. Can substitute for Evade.",
  "forceful strike": "Reduce Combat Skill by 1 Grade, then Dmg Mod is increased 2 Grades.",
  "graceful strike": "If Unburdened & no armor, Dmg Mod is DEX+POW instead of STR+SIZ if higher.",
  "grand master": "See description.",
  "great hearing": "Perception rolls via hearing are 1 Difficulty Grade easier.",
  "greater brute strength": "2x/day, increase Brawn by 1 Difficulty Grade easier.",
  "greater holy smite": "Increase Dmg Mod by 3 steps against undead, demons, or devils.",
  "greater sweeping strike": "If you drop your first foe, immediate attack on all other foes in range.",
  "greater turning": "When Turning Undead, you may reroll, but must take 2nd roll.",
  "heart slow": "Appear dead by choice.",
  "hide in shadows": "If in shadow or dark, all Perception rolls are 1 Diff. Grade harder.",
  "high master": "See description.",
  "holy smite": "Increase Dmg Mod by 1 step against undead, demons, or devils.",
  "holy strike": "1/day per Rank, deal +1d6 damage to an Evil creature. See description.",
  "hospitality": "You get food & lodgings from other paladins or cavaliers.",
  "identify plants and animals": "Identify mundane plants & animals w/no chance of failure. See description.",
  "identify pure water": "Identify water w/no chance of failure.",
  "illusion sensitivity": "Detect Illusions at 1 Grade Easier. Phantasms are normal Diff. Grade.",
  "immune to charm spells": "Immune to Charm by bards, dryads, nymphs, etc.",
  "immunity to disease": "Immune to natural diseases. See description.",
  "immunity to fear": "Immune to fear in 10' radius. Extends to those in radius.",
  "immunity to poison": "Immune to poison & venom.",
  "improved holy smite": "Increase Dmg Mod by 2 steps against undead, demons, or devils.",
  "indomitable": "Immune to all forms of mind control or domination.",
  "innate magic": "May cast spells w/o spellbook. See description.",
  "inspire competence": "Allies get +10% to all skills for 1 Round. See description.",
  "inspire courage ii": "Allies get +10% to all skills for 2 Rounds. See description.",
  "inspire courage iii": "Allies get +15% to all skills for 3 Rounds. See description.",
  "inspire greatness": "While performing, allies get +10% to all skills up to 5 Rounds per Rank. See description.",
  "inspire heroics": "Allies get +20% to all Resistance Rolls. See description.",
  "just a scratch": "1x/day, you regain Hit Points = Healing Rate in 1 Hit Location.",
  "keen senses": "Superior hearing and smell; Perception rolls are 1 Diff. Grade easier.",
  "ki strike": "Your Unarmed attacks are considered magical.",
  "lay on hands": "1/day per Rank, spend 1 Round & heal all lost HP from a Minor Wound to a single Hit Location.",
  "legendary sorcerer": "Cast spells without verbal, somatic, or materials.",
  "lightning reflexes": "If Extremely Unburdened & wearing no armor, +10% to Parry & Evade skills.",
  "magic resistance": "1 Difficulty Grade bonus in Willpower rolls vs magic. See description.",
  "mental strength 1": "1x/day, 2 Grades easier in Willpower checks.",
  "mental strength 2": "2x/day, 2 Grades easier in Willpower checks.",
  "mental strength 3": "3x/day, 2 Grades easier in Willpower checks.",
  "mental strength 4": "4x/day, 2 Grades easier in Willpower checks.",
  "mental strength 5": "5x/day, 2 Grades easier in Willpower checks.",
  "mental strength i": "1x/day, 2 Grades easier in Willpower checks.",
  "mental strength ii": "2x/day, 2 Grades easier in Willpower checks.",
  "mental strength iii": "3x/day, 2 Grades easier in Willpower checks.",
  "mental strength iv": "4x/day, 2 Grades easier in Willpower checks.",
  "mental strength v": "5x/day, 2 Grades easier in Willpower checks.",
  "mounted combat mastery": "Combat Skills not limited to Ride; Mounted Charge is standard. See description.",
  "mounted combat": "Combat Skills not limited to Ride; Mounted Charge is standard.",
  "mystic healing": "Regain 2x Healing Rate in Hit Points. See description.",
  "natural light": "Emits a soft glow up to 10 feet. This makes Stealth rolls one Difficulty Grade harder.",
  "nether walk": "Teleport 1/10 Mysticism in feet.",
  "overrun": "When Charging & you drop opponent, you may attack another in your path.",
  "pain control": "All Endurance rolls are Automatic Successes.",
  "pass without a trace": "Move @ normal pace & leave no trail.",
  "perfection": "Immune to Charm spells, 10 AP, & enter ethereal state for 20 Rounds.",
  "poison resistance": "Endurance rolls vs poison are 1 Grade easier.",
  "powerful concentration": "Willpower tests for Concentration are 1 Grade Easier.",
  "protection from evil": "Permanent version of spell (see spell).",
  "quick": "Movement Rate is +5' per Rank if Extremely Unburdened.",
  "quivering palm": "Kill with a touch. See description.",
  "radiant burst": "1/day and 1 Action Point, release burst of energy. See description for details.",
  "ranged specialist 1": "Shift Hit Location 1 spot (if in Close Range).",
  "ranged specialist 2": "In Close Range, double Critical chance. +1 step to Damage Mod.",
  "ranged specialist i": "Shift Hit Location 1 spot (if in Close Range).",
  "ranged specialist ii": "In Close Range, double Critical chance. +1 step to Damage Mod.",
  "ranged specialist": "Shift Hit Location 1 spot (if in Close Range).",
  "ranged touch": "Extend Touch spells to 30'.",
  "read languages": "Decipher written languages. See description.",
  "resilient": "Hit Points calculated with STR+CON+SIZ.",
  "resistance to sleep and charm": "Willpower rolls against sleep and charm spells are 2 grades easier.",
  "second wind": "1x/day, during brief rest, recover up to 3 levels of Fatigue.",
  "shape change 1": "Transform into mundane reptile, bird, or mammal w/out Magic Points.",
  "shape change 2": "Transform into tiny animals w/out Magic Points. See description.",
  "shape change 3": "Transform into S, M, or L elemental. See description.",
  "shape change 4": "Transform into Huge elemental 1/day. See description.",
  "shape change i": "Transform into mundane reptile, bird, or mammal w/out Magic Points.",
  "shape change ii": "Transform into tiny animals w/out Magic Points. See description.",
  "shape change iii": "Transform into S, M, or L elemental. See description.",
  "shape change iv": "Transform into Huge elemental 1/day. See description.",
  "sharp eyed": "Perception rolls via sight are 1 Difficulty Grade easier.",
  "sharp vision": "Perception rolls via sight are 1 Difficulty Grade easier.",
  "shell parry": "For 1 Action Point, retreat into your shell. See description.",
  "skirmishing": "Launch ranged attacks while running, but attack = Athletics.",
  "slow fall": "If Unburdened & wearing no armor, can fall 1/2 Mysticism in feet w/o damage.",
  "sneak attack": "Neutralize a victim w/melee or ranged weapon. See description.",
  "song of freedom": "Break Enchantment or Charms. See description.",
  "sorcery spellcaster": "Cast spells as a sorcerer. See description.",
  "spatial awareness": "If attacked from behind, make Formidable Perception to turn & face before they strike.",
  "speak with animals": "Understand & be understood by 1 specific animal. Chosen animal:",
  "speak with plants": "Speak to & be understood by natural vegetation.",
  "species enemy 1": "+10% bonus when fighting enemy. Chosen enemy:",
  "species enemy 2": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy 3": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy 4": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy 5": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy i": "+10% bonus when fighting enemy. Chosen enemy:",
  "species enemy ii": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy iii": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy iv": "+10% bonus when fighting enemy. New chosen enemy:",
  "species enemy v": "+10% bonus when fighting enemy. New chosen enemy:",
  "spell-like abilities": "Use SPELLNAME like the spell.",
  "spell-like ability": "Use SPELLNAME like the spell.",
  "spontaneous casting": "Cast spells with Arcane Sorcery roll.",
  "stealthy": "If wearing Light armor, Stealth rolls are 1 Difficulty Grade easier.",
  "subterfuge": "All Lockpicking, Mechanism, & Sleight rolls are 1 Diff. Grade Easier.",
  "suggestion": "See Suggestion spell.",
  "survival bonus": "Survival rolls related to your area of origin are 1 Diff. Grade easier.",
  "swashbuckling": "If Unburdened & wearing Light armor, Attack & Evade not limited by Athletics.",
  "sweeping strike": "If you drop your first foe, immediate attack allowed on another nearby foe.",
  "swimmer": "Auto succeed while swimming except in a difficult task. See description.",
  "tail balance": "Athletics rolls for climbing or balancing are 1 Diff. Grade easier.",
  "thirsty": "Must drink more water. Normal dehydration begins after CONx3 hours.",
  "tunnel sense": "Detect pits, deadfalls, traps and more underground w/Easy Perception roll.",
  "turn undead": "You can drive or destroy undead or Evil beings. See description.",
  "unarmed proficiency": "You gain +5% to your Unarmed. Noted already above.",
  "unarmored defense": "If Unburdened & wearing no armor, Evade is 1 Grade Easier.",
  "use arcane scrolls": "Cast arcane spells w/o using Read Magic. See description.",
  "vaulting": "If Unburdened, can use Acrobatics to pole vault over obstacles. See description.",
  "very agile": "If Extremely Unburdened & wearing no armor, add 1/10 Mysticism to your Initiative, min. 5. Noted above.",
  "weapon master": "Dbl Critical in your chosen weapon specialization.",
  "weapon precision": "When using small weapons, Dmg Mod is based on STR+DEX.",
  "weapon specialization": "Specialize in 1 weapon. See description. Weapon:",
  "wild casting": "Cast spells while shape changed.",
  "woodland languages": "Add 1 Language of woodland species at INT+CHA+40.",
  
  // Additional class abilities
  "fascinate": "Use Musicianship to entrance creatures within 90'. See description.",
  "inspire courage i": "Allies get +5% to all skills for 1 Round. See description.",
  "commanding presence": "Allies within 30' gain +10% to Willpower rolls.",
  "tactical shift": "As a free action, allow one ally to move 5' without provoking attacks.",
  "commander": "Grant an ally an immediate extra action. See description.",
  "battle captain": "Grant multiple allies immediate actions. See description.",
  "war marshal": "Coordinate large-scale tactical movements. See description.",
  "lord commander": "Supreme battlefield command abilities. See description.",
  "legendary master": "Ultimate weapon mastery. See description."
};

/**
 * Get description for an ability
 * @param {string} abilityName - The ability name
 * @returns {string|null} - The description or null if not found
 */
AbilityDescriptions.getDescription = function(abilityName) {
  if (!abilityName) return null;
  const normalized = abilityName.toLowerCase().trim();
  return this[normalized] || null;
};

/**
 * Check if an ability has a known description
 * @param {string} abilityName - The ability name
 * @returns {boolean}
 */
AbilityDescriptions.hasDescription = function(abilityName) {
  if (!abilityName) return false;
  const normalized = abilityName.toLowerCase().trim();
  return this.hasOwnProperty(normalized);
};

/**
 * Get all ability names
 * @returns {Array} - Array of all ability names (lowercase)
 */
AbilityDescriptions.getAllAbilities = function() {
  return Object.keys(this).filter(key => typeof this[key] === 'string');
};

// Make available globally
window.AbilityDescriptions = AbilityDescriptions;
