/**
 * Spell Data for Mythras Classic Fantasy
 * Contains spell names, costs, and descriptions
 */

const SpellData = {
  // Spell descriptions for tooltips
  descriptions: {
    // === Cantrips (Rank 0) ===
    "appraise": "Quickly gauge the approximate value and quality of an item by inspection.",
    "avert": "Dismiss another Rank 0 Spell within Range or reactively neutralize one being cast using Counter Magic.",
    "babble": "Twist a target's speech into confused nonsense, hindering clear commands and casting.",
    "beastcall": "Call a small group of nearby mundane animals of a chosen type to your location.",
    "befuddle": "Cloud a target's thinking, making concentration and reasoned actions more difficult.",
    "calculate": "Perform rapid, precise mental arithmetic and bookkeeping with uncanny accuracy.",
    "calm": "Dampen down the Passions of a humanoid target.",
    "calm animal": "Calm a panicked or hostile animal, making it regain composure or back down.",
    "chill": "Dramatically reduce the temperature of a small object, leaving it cold to the touch.",
    "heat": "Dramatically increase the temperature of a small object, leaving it warm or hot to the touch.",
    "chill (heat)": "Dramatically reduce or increase the temperature of small objects.",
    "cleanse": "Rid an object, person, or small area of dirt, grease, grime, and bad smells.",
    "dishevel": "Cover objects or creatures in grime, dust, and cobwebs, making them appear dirty.",
    "cleanse (dishevel)": "Clean an object/area to spick-and-span state, or cover it in grime and dust.",
    "coordination": "Enhance manual dexterity for a single task, permitting a re-roll of an agility skill check.",
    "deflect": "Ward the recipient against tiny impacts like rain drops, midges, or flying sand.",
    "dry": "Remove all extraneous moisture from an object or person up to POW x2 in SIZ.",
    "fanaticism": "Temporarily flood a target with excessive, irrational devotion or zeal.",
    "demoralize": "Temporarily fill a target with despondency and doubt toward a cause or subject.",
    "fanaticism (demoralize)": "Fill target with wildly excessive devotion, or despondency toward something.",
    "frostbite": "Inflict numbness and pain in one of the recipient's extremities.",
    "glamour": "Make the target subtly alluring so people are naturally drawn to them.",
    "repugnance": "Twist the target so that they provoke quiet distaste or avoidance in others.",
    "glamour (repugnance)": "Make target alluring, or cause them to provoke distaste in observers.",
    "glue": "Cement together two solid, inanimate objects for the Duration of the spell.",
    "ignite": "Cause a small piece of flammable inorganic matter to burst into flame.",
    "extinguish": "Immediately snuff out modest flames and small fires within reach.",
    "ignite (extinguish)": "Cause flammable matter to ignite, or immediately quench small fires.",
    "incognito": "Alter facial features to a bland, unmemorable countenance that is overlooked.",
    "ironhand": "Hold anything that would otherwise cause damage without injuring yourself.",
    "magic tricks": "Produce tiny, harmless magical effects for entertainment or minor convenience.",
    "magnify": "See something twice as close as it really is, useful for close work or at distance.",
    "might": "Add caster's POW to recipient's Brawn skill for an impressive act of physical strength.",
    "mimic": "Perfectly mimic the voice and mannerisms of someone the caster has seen and heard.",
    "mobility": "Increase Movement Rate of the recipient by 5' (01-70) or 10' (71-00) for the Duration.",
    "perfume": "Negate a noxious odor or imbue an odorless substance with a pleasing fragrance.",
    "pet": "Take mental control of a small creature to scout, fetch, or perform complex tasks.",
    "polish": "Instantly buff an object to a high sheen, making it glossy and highly desirable.",
    "preserve": "Prevent organic matter from bacterial decay and putrefaction for 1d3 Months.",
    "protection": "Reduce first damage that penetrates protection by 1d3 points when triggered.",
    "repair": "Fix physical damage to an inanimate object, repairing 1d3 HP per casting.",
    "spiritshield": "Create a shield that deters spirits and ghosts from entering.",
    "tidy": "Restore several items (up to caster's POW) to a neat, tidy, and orderly fashion.",
    "tune": "Ensure a musical instrument is in perfect pitch regardless of conditions.",
    "voice": "Amplify intonation and delivery so all who hear must listen to verbal commands.",

    // === Rank 1 Spells ===
    "acid arrow": "A magical arrow of acid flies toward target, dealing 1d4 acid damage per Round for 1d2 Rounds.",
    "affect normal fires": "Command small fires to reduce to candle flame or grow to bonfire (3' diameter max).",
    "alarm": "Select an object or area to produce a loud ringing if interacted with or entered.",
    "animal friendship": "One animal up to 6 SIZ per Intensity must make Willpower roll or stand transfixed.",
    "armor": "Subject gains invisible force field equal to scale armor (4 AP to each Hit Location).",
    "audible illusion": "Create an illusionary audible noise at any point within range, movable at will.",
    "barkskin": "Target's skin toughens to bark equivalent: 2 AP +1 per full 3 Intensity. Stacks with armor.",
    "bind": "Command up to 20' of rope per Intensity to coil, loop, knot, tie, and vice versa.",
    "bless": "Bless a single item or group of allies within Area of Effect.",
    "curse": "Afflict a target with ill fortune, making their efforts more likely to fail.",
    "bless (curse)": "Bless allies to bolster them or curse foes to hinder them.",
    "blindness": "Blind one target, reducing their sight to only a deep grayness.",
    "blur": "Blur your form, causing all physical attacks against you to increase one Difficulty Grade.",
    "ceremony": "Perform customs, rituals and rites specific to various religions, varying by Rank.",
    "change appearance": "Alter appearance to any humanoid or person-shaped bipedal form.",
    "charm being": "Influence a sapient creature to regard you as a trusted friend and ally.",
    "chill touch": "Deliver a freezing touch that chills and weakens living flesh.",
    "color cascade": "Unleash a fan of shifting colors that can dazzle or disorient creatures.",
    "combine": "Let multiple casters pool power into a single spell casting or Turning Undead.",
    "command": "Force a creature to obey a single-word order for a brief instant.",
    "create water": "Conjure 8 gallons of fresh, drinkable water from nothing.",
    "destroy water": "Cause 8 gallons of existing water to evaporate or become useless.",
    "create water (destroy water)": "Conjure fresh water or banish existing water within 8 gallons.",
    "cure fatigue": "Soothe away a target's exhaustion, restoring their energy.",
    "cause fatigue": "Magically sap a target's vigor, leaving them tired and sluggish.",
    "cure fatigue (cause fatigue)": "Remove weariness from a creature or impose draining fatigue.",
    "cure minor wounds": "Close small cuts and bruises, restoring a modest amount of health.",
    "cause minor wounds": "Magically tear flesh or bruise a target, dealing minor harm.",
    "cure minor wounds (cause minor wounds)": "Mend small injuries or inflict minor magical wounds.",
    "deafness": "Block a target's hearing with magic, preventing them from perceiving sound.",
    "detect charm": "Sense whether a creature is under the effects of Charm Being.",
    "hide charm": "Mask charm effects on a creature from detection magic.",
    "detect charm (hide charm)": "Sense Charm Being on targets or conceal such enchantments.",
    "detect evil": "Perceive the presence and direction of Evil within a 10' path to Range.",
    "detect good": "Perceive the presence and direction of strongly Good beings within a 10' path.",
    "detect evil (detect good)": "Discern the presence of beings or auras of strong moral Alignment.",
    "detect illusion": "Reveal the presence of illusions and help distinguish them from reality.",
    "detect magic": "Sense nearby magical auras, items, and active spells within a 10' wide, 60' long path.",
    "detect poison": "Determine if a creature, object, or food within 5' has been tainted with poison.",
    "detect snares and pits": "Reveal hidden pits, snares, and simple environmental traps.",
    "detect undead": "Sense undead within a range of 60'.",
    "disk of burden": "Create a floating 3' disk of force that follows you and carries loads.",
    "dust devil": "Conjure a small air elemental that can harass foes and obscure vision.",
    "endure heat/cold": "Protect the target from harm and discomfort caused by extreme temperatures.",
    "enlarge": "Increase a creature's or object's size and strength within safe limits.",
    "reduce": "Shrink a creature or object, making it smaller and easier to move or conceal.",
    "enlarge (reduce)": "Enlarge or shrink a chosen target, altering its size and mass.",
    "entangle": "All vegetation in Area of Effect comes to life and entangles creatures.",
    "erase writing": "Erase all writing from one or two sheets, a scroll, or one spell from a spellbook.",
    "faerie fire": "Outline creatures or objects in glowing light, making them easier to hit.",
    "faerie lights": "Create 1d4 flickering lights, glowing spheres, or a humanoid shape of light.",
    "familiar": "Bind a small creature as a magical companion that shares a link with you.",
    "feather fall": "Slow the rate of falling so creatures or objects land safely.",
    "find traps": "Reveal nearby mundane and magical traps, though not always how to disarm them.",
    "flame blade": "Conjure a blazing scimitar-like melee weapon of fire that burns on contact.",
    "flaming hands": "Project a 120° cone of fire, 5' long. Damage depends on Intensity.",
    "friendship": "Targets who fail Resistance Roll want to befriend you, social skills 1 Grade easier.",
    "goodberry": "Empower 2d4 berries to provide nourishment and minor healing when eaten.",
    "badberry": "Twist 2d4 berries so they sicken or slightly harm those who eat them.",
    "goodberry (badberry)": "Enchant 2d4 berries to heal and feed—or harm and sicken—those who partake.",
    "grease": "Coat a surface or object in slick grease, making footing or grip treacherous.",
    "hypnotism": "One subject per Intensity finds caster's movements mesmerizing, susceptible to suggestions.",
    "identify": "Attempt to identify the magical properties (if any) of one item or object.",
    "illusion, lesser": "Create a small, simple illusion to mislead or distract observers.",
    "lesser illusion": "Create a small, simple illusion to mislead or distract observers.",
    "invisibility, lesser": "Subject and carried gear disappears, invisible to all natural sight.",
    "lesser invisibility": "Subject and carried gear disappears, invisible to all natural sight.",
    "invisibility to animals": "Cause normal animals to overlook or ignore the target.",
    "invisibility to undead": "Prevent undead from noticing the target unless provoked.",
    "jump": "Extend jumping distance: 10' up, 30' forward, or 10' backward.",
    "know languages": "Understand spoken non-magical languages you hear for the duration.",
    "confuse languages": "Twist speech so listeners hear jumbled or nonsensical words.",
    "know languages (confuse languages)": "Grant understanding of non-magical speech or scramble it.",
    "leonard's false trap": "Place a false trap on a small mechanism to deceive a potential thief.",
    "levitate": "Raise or lower a creature or object along a vertical line with limited control.",
    "light": "Cause an object to shed bright light like a lantern.",
    "light (darkness)": "Create bright magical light or deepen surrounding shadows.",
    "locate animals or plants": "Sense the direction of a specific kind of animal or plant nearby.",
    "magic aura": "Imbue an object with a magical aura so it detects positively as magical.",
    "magic missile": "Fire one or more bolts of force that strike one or more targets.",
    "magical stone": "Charge small stones so they strike as potent thrown weapons.",
    "message": "Whisper to one creature per Intensity; targeted creatures can whisper back.",
    "messenger": "Send a small creature or spirit to carry a brief message to a target.",
    "misdirection": "Misdirect the results of a detection spell if subject Fails Resistance Roll.",
    "pass without trace": "Move through terrain leaving no discernible trail, scent, or evidence.",
    "predict weather": "Foresee near-future weather within a 5-mile radius with reliable accuracy.",
    "protection from cantrips": "Grant resistance to minor magical tricks and nuisance cantrips.",
    "protection from evil": "Ward the target against creatures and influences of malign Alignment.",
    "protection from good": "Ward the target against creatures and influences of benevolent Alignment.",
    "protection from evil (protection from good)": "Create a warding aura against creatures of chosen Alignment.",
    "purify food and drink": "Cleanse provisions of spoilage, disease, and simple toxins.",
    "contaminate food and drink": "Subtly taint provisions so they sicken or harm those who partake.",
    "purify food and drink (contaminate food and drink)": "Render food/drink safe or secretly corrupt it.",
    "read magic": "Decipher magical writings, glyphs, and scrolls. Key spell for mages and bards.",
    "reflect gaze": "Turn gaze-based effects aside or back toward their source.",
    "remove fear": "Calm anxieties and bolster courage, driving out magical fear.",
    "cause fear": "Instill supernatural dread that can send creatures fleeing.",
    "remove fear (cause fear)": "Banish fear from allies or conjure it in your foes.",
    "sanctuary": "Shroud you in divine protection that discourages enemies from attacking.",
    "secure portal": "Magically reinforce a door or gate against opening as if it were locked.",
    "shield": "Create an invisible disk of force providing 4 AP against attacks from that direction.",
    "shillelagh": "Empower a club or staff so it strikes harder and more reliably.",
    "shocking touch": "Deliver a crackling jolt doing 1d6 damage +1 per Intensity through touch.",
    "silence": "Create a zone in which no sound can be made or heard.",
    "sleep": "Lull creatures in 10' radius into sudden magical slumber (if they fail Willpower).",
    "slow poison": "Delay the effects of poison or venom, buying time for a cure.",
    "spider climb": "Walk on walls and ceilings like a spider at 10' Movement Rate.",
    "uncontrollable horrible laughter": "Overwhelm a creature with manic laughter, leaving it helpless and prone.",
    "unseen servant": "Summon an invisible force that performs simple, repetitive tasks on command.",
    "ventriloquism": "Project your voice so it seems to come from another place or creature.",

    // === Rank 2 Spells ===
    "aid": "Grant ally +5% to all skill rolls and +2 temporary HP to all Hit Locations; stacks with Bless.",
    "alter self": "Briefly reshape your body to adopt a different humanoid-shaped biped form.",
    "augury": "Seek a brief omen about whether a planned action within 30 min brings weal or woe.",
    "blink": "Randomly teleport between locations, making you difficult to target.",
    "breathe water": "Allow a creature to breathe water as easily as air while the spell lasts.",
    "breathe air": "Allow a normally aquatic creature to breathe air comfortably.",
    "breathe water (breathe air)": "Let a creature breathe comfortably in water or air.",
    "call lightning": "If weather permits, summon bolts of lightning from storm clouds to strike foes.",
    "chant": "Strengthen allies (+5% skills, +1 damage/Intensity) and weaken foes while maintained.",
    "charm being or mammal": "Enchant a sapient creature or mammal so it regards you as a trusted friend.",
    "clairaudience": "Magically listen to sounds from a distant location within a 60' radius.",
    "clairvoyance": "Magically see a distant location within a 60' radius as if present there.",
    "clairaudience/clairvoyance": "Perceive a distant location within 60' through magical hearing or sight.",
    "commune with nature": "Learn broad information about terrain, plants, animals in surrounding area.",
    "continual light": "Create permanent magical light equal to full daylight until dispelled.",
    "continual darkness": "Create persistent magical darkness that suppresses normal light.",
    "continual light (continual darkness)": "Create lasting magical light or lasting field of magical darkness.",
    "create food and water": "Conjure nourishing food and water for up to 3 creatures of SIZ 20 or less.",
    "cure blindness or deafness": "Restore sight or hearing from magical or mundane causes.",
    "cause blindness or deafness": "Magically rob a creature of sight or hearing.",
    "cure blindness or deafness (cause blindness or deafness)": "Restore or inflict magical blindness/deafness.",
    "cure disease": "Purge mundane and magical disease with Potency < Intensity x20.",
    "cause disease": "Infect a creature with debilitating disease with Potency < Intensity x20.",
    "cure disease (cause disease)": "Cleanse a creature of disease or afflict it with crippling malady.",
    "cure serious wounds": "Mend deep injuries to one Hit Location, up to Serious Wound severity.",
    "cause serious wounds": "Reduce a single Hit Location to 0 HP, plus 1d3+1 damage.",
    "cure serious wounds (cause serious wounds)": "Heal any Serious Wound or inflict the same on a target.",
    "darkness": "Shroud an area in inky magical darkness that normal light cannot penetrate.",
    "darkvision": "Grant recipient Darkvision out to 60 feet as per the Class Ability.",
    "detect invisibility": "See invisible objects or beings, including hidden, ethereal, or out of phase targets.",
    "dispel magic": "All magic within 15' radius of target point is subject to dismissal.",
    "enfeeblement": "Impose two Difficulty Grade penalty to all skill rolls and Damage Modifier.",
    "feign death": "Place a willing creature into a death-like state indistinguishable from actual death.",
    "fireball": "Detonate a blazing 20' radial sphere of flame that burns creatures in a wide area.",
    "fire trap": "Enchant a container or door so opening it triggers a burst of fiery damage.",
    "flame arrow": "Transform arrows/bolts into fiery projectiles, or create a bolt of searing flame.",
    "flame strike": "Call down a 30' column of divine fire doing 1d8 damage per 2 Intensity.",
    "flame walk": "Allow one creature per Intensity to endure temperatures up to 2,000°F.",
    "fly": "Grant flight to one creature up to 3 SIZ per Intensity. 30' Movement Rate.",
    "forget": "Cause 1-4 creatures who fail Willpower to forget the 5 minutes prior to casting.",
    "gust of wind": "Create 40 mph winds (STR 60+1d12) along a path 10' wide, 30' long per Intensity.",
    "haste": "Double Movement Rate, +4 Initiative, add 2 extra defensive Action Points.",
    "heat metal": "Cause 5 ENC per Intensity of ferrous metal worn/carried to heat up painfully.",
    "chill metal": "Cause 5 ENC per Intensity of ferrous metal worn/carried to cool down painfully.",
    "heat metal (chill metal)": "Dangerously raise or lower temperature of metal worn or held.",
    "hold animal": "Paralyze a mundane animal that loses Opposed Willpower, leaving it helpless.",
    "hold person": "Paralyze a humanoid that loses Opposed Willpower, rendering them immobile but aware.",
    "hold undead": "Paralyze undead that lose Opposed Willpower, freezing them in place.",
    "illusion, greater": "Create a complex, more convincing illusion of sights and sounds.",
    "greater illusion": "Create a complex, more convincing illusion of sights and sounds.",
    "invisibility (10ft)": "All individuals within 10' of the original recipient are rendered invisible.",
    "know passions": "Discern the Passions and Alignment of one creature.",
    "obscure passions": "Hide the Passions and Alignment of one creature from scrutiny.",
    "know passions (obscure passions)": "Reveal a creature's Passions and Alignment or cloud them.",
    "leonard's tiny magic hut": "Create a secure magical shelter holding up to 100 SIZ, protecting from weather.",
    "lightning bolt": "Project a searing line of lightning that blasts through creatures in its path.",
    "locate object": "Sense the direction of a familiar or known object within range.",
    "obscure object": "Hide an item from detection spells that would normally locate it.",
    "locate object (obscure object)": "Home in on a desired object or shield it from magical detection.",
    "mage lock": "Magically seal a door or portal, resisting mundane attempts to open.",
    "magic mouth": "Enchant an object to deliver a spoken message of up to 5 words per Intensity.",
    "minute meteors": "Summon small flaming spheres to hurl as fiery missiles, doing 1d6 damage.",
    "mirror images": "Create 2d4 illusory duplicates within 5' radius that mimic your movements.",
    "monster summoning, lesser": "Call minor creatures to aid you in battle or tasks for a short time.",
    "obscurement": "Shroud an area in thick mist, reducing visibility to 5'.",
    "plant growth": "Cause plants within 1/2 mile to thicken, hindering movement or enriching land.",
    "produce flame": "Conjure a flame in your hand for light or to hurl and burn foes.",
    "protection from cold": "Ward a creature against extreme cold and cold-based attacks.",
    "protection from evil 10' radius": "Create a protective 10' aura warding against Evil entities.",
    "protection from good 10' radius": "Create a protective aura warding against Good Alignment entities.",
    "protection from evil 10' radius (protection from good 10' radius)": "Protective field against beings of chosen Alignment.",
    "protection from fire": "Shield completely from natural fire; absorb 12 magical fire damage/Intensity.",
    "protection from mundane missiles": "Grant resistance or immunity to normal, non-magical missiles.",
    "pyrotechnics": "Transform an existing fire into blinding fireworks or choking smoke.",
    "read thoughts": "Glance into a creature's surface thoughts if it fails Opposed Willpower.",
    "remove curse": "Lift a magical curse from a creature or object, ending its malign effect.",
    "bestow curse": "Afflict a target with a persistent, harmful curse of your choosing.",
    "remove curse (bestow curse)": "Dispel a harmful curse or lay a new one upon a target.",
    "remove paralysis": "Free 1-4 creatures from magical or mundane paralysis.",
    "scare": "Fill weaker creatures with sudden magical terror that may send them fleeing.",
    "sigil of warding": "Inscribe a magical symbol that triggers an effect when disturbed.",
    "slow": "Hinder Movement Rate and Initiative of one creature per Intensity.",
    "snake charm": "Mesmerize or pacify up to 10 SIZ of snakes per Intensity.",
    "snare": "Set an invisible magical trap that hoists or entangles creatures that trigger it.",
    "speak with animals": "Hold simple conversations with one type of mundane animal within 30'.",
    "speak with dead": "Briefly question a corpse's spirit. Questions depend on Intensity.",
    "spectral hand": "Conjure a ghostly hand that delivers touch spells at a distance.",
    "spiritual hammer": "Manifest a floating 3 AP force-weapon that strikes under your command.",
    "stinking cloud": "Create a nauseating cloud that sickens and disables creatures inside.",
    "strength": "Enhance physical might (+4 STR, +5% to Brawn and STR-based skills).",
    "suggestion": "Seed a compelling idea into a creature's mind that fails Willpower, up to 1 hr/Intensity.",
    "summon insects": "Call a swarm of biting or stinging insects to harry and distract foes.",
    "tongues": "Allow the subject to speak and understand any one language.",
    "confuse tongues": "Twist speech so listeners hear gibberish or the wrong words.",
    "tongues (confuse tongues)": "Grant fluency in one language or twist speech into nonsense.",
    "tree": "Merge into a living tree, hiding within while remaining dimly aware of surroundings.",
    "trip": "Cast on a loose object up to 10' long, causing it to trip creatures passing over it.",
    "unlock": "Magically open a single locked mechanism without the key.",
    "lock": "Magically secure a door, chest, or similar mechanism more securely.",
    "unlock (lock)": "Open a secured object or reinforce it with magical locking.",
    "vampiric touch": "Drain Hit Points from each of the target's Hit Locations, gaining them yourself.",
    "warp wood": "Bend or twist wooden objects, warping them out of shape or utility.",
    "straighten wood": "Restore warped or bent wooden objects to their proper form.",
    "warp wood (straighten wood)": "Distort wooden items or return them to usable condition.",
    "water walk": "Walk on surface of liquids as though on solid ground.",
    "web": "Thick sticky strands shoot from your hand to block movement or entangle foes. Not flammable.",

    // === Rank 3 Spells ===
    "aerial servant": "Summon an invisible entity to retrieve a specified creature or item.",
    "air walk": "Walk on air as solid ground. May ascend/descend at up to 45 degrees. Up to SIZ 50.",
    "animal growth": "Cause animals to grow in size and power, enhancing strength and ferocity.",
    "shrink animal": "Reduce an animal to a much smaller size for transport or concealment.",
    "animal growth (shrink animal)": "Enlarge an animal to imposing size or shrink it to manageable form.",
    "animal summoning i": "Call one or more normal or giant-sized mundane animals to aid you.",
    "animate dead": "Animate corpses to create skeletons or zombies depending on decay state.",
    "anti-plant shell": "Create an invisible globe shielding from hostile plants or plant-creatures.",
    "atonement": "Lift burden of actions the subject didn't know they committed or was forced to perform.",
    "big interposing hand": "Conjure a massive magical hand that blocks attacks, targets, and movement.",
    "call woodland beings": "Summon fey or woodland creatures to assist. Wilderness areas only.",
    "charm monster": "Enthrall living creatures up to 20 SIZ (or one of any SIZ) to view you as ally.",
    "cloud kill": "Create a 40' long toxic fog cloud, 30' high and deep. Holding breath offers no protection.",
    "cloudkill": "Create a 40' long toxic fog cloud, 30' high and deep. Holding breath offers no protection.",
    "commune": "Enter trance to contact your deity. Ask one yes-or-no question per Intensity.",
    "cone of cold": "Unleash a 90° cone of cold, 10' per Intensity. 1d6+1 damage per 2 Intensity.",
    "confusion": "1d3 creatures in Area of Effect who fail Resistance Roll become magically confused.",
    "conjure elemental": "Summon a powerful elemental, risking loss of control if concentration fails.",
    "control temperature 10' radius": "Raise or lower ambient temperature within 10' by up to two Difficulty Grades.",
    "control winds": "Significantly alter the current wind strength using the Wind Table.",
    "cure major wounds": "Heal anything up to a Major Wound in one Hit Location, even if dismembered.",
    "cause major wounds": "Reduce a single Hit Location to negative value equal to its full HP, maiming it.",
    "cure major wounds (cause major wounds)": "Restore a Major Wound or inflict one, maiming the target.",
    "detect lie": "Reveal whether a single being is knowingly lying or withholding truth.",
    "undetectable lie": "Conceal lies from magical detection for 6 hours per Intensity.",
    "detect lie (undetectable lie)": "Reveal lying or conceal lies from magical scrutiny.",
    "dimension door": "Instantly travel 100' per Intensity without crossing intervening space.",
    "dispel evil": "Empower the cleric to banish Evil entities from other planes with a touch.",
    "banish good": "Banish Good-aligned extraplanar beings with a touch.",
    "dispel evil (banish good)": "Banish Evil forces or banish the influence of Good-Aligned beings.",
    "divination": "Receive specific divine insight about an event expected within the next week.",
    "domination": "Take control of an individual who Fails Resistance Roll for 1 week per Intensity.",
    "enchant weapon": "Temporarily imbue a normal weapon with a +1 Damage Bonus.",
    "exorcism": "Call upon your deity to expel a spirit or supernatural force possessing a being.",
    "fear": "Send a wave of supernatural terror. Creatures who fail flee at sprinting speed.",
    "feeblemind": "Reduce any sapient creature that fails Willpower to INT 3 and -1 Action Point.",
    "free action": "Subject acts normally regardless of spells, effects, or terrain that would hinder.",
    "fumble": "Opponents who fail Willpower become clumsy. Failures treated as Fumbles.",
    "hallucinatory forest": "Create a forest of illusion, completely real in every respect.",
    "hail/ice storm": "Summon a destructive storm of ice, hail, and freezing winds.",
    "ice storm": "Summon a destructive storm of ice, hail, and freezing winds.",
    "heat/cold shield": "Create a shield of wispy flames protecting from fire or cold, depending on variant.",
    "hold monster": "Immobilize one creature per Intensity (max four) within Area of Effect.",
    "hold plant": "Immobilize one plant per Intensity (max four), including sapient vegetation.",
    "illusionary terrain": "Mask terrain within Area of Effect with an illusion of your choosing.",
    "illusion, advanced": "Create an illusion without Concentration, including visual, auditory, olfactory, thermal.",
    "advanced illusion": "Create an illusion without Concentration, including visual, auditory, olfactory, thermal.",
    "insect plague": "Summon a thick cloud of flying, crawling, and jumping insects from the environment.",
    "invisibility, greater": "Render a creature nearly impossible to detect by sight, even if they attack.",
    "greater invisibility": "Render a creature nearly impossible to detect by sight, even if they attack.",
    "legend lore": "Gain information about any legend connected to an object, location, or individual.",
    "leonard's secure cottage": "Conjure a cottage with door, windows, fireplace. 200 sq ft per Intensity.",
    "lesser creation": "Conjure a mundane object made of non-living material, up to 5 ENC per Intensity.",
    "lower water": "Cause water to lower by 2' per Intensity, to a maximum depth of 1 inch.",
    "raise water": "Cause water to rise or swell, altering depth or flow.",
    "lower water (raise water)": "Lower or elevate water levels within a broad area.",
    "monster summoning": "Call powerful extraplanar creatures to assist you temporarily.",
    "neutralize poison": "Cancel poison effects. Can revive poisoning death if cast within 10 minutes.",
    "inflict poison": "Introduce a deadly toxin into a living target.",
    "neutralize poison (inflict poison)": "Cleanse a creature of poison or afflict them with magical toxins.",
    "pass wall": "Create a 5' wide, 8' high, 10' deep passage through stone, wood, or plaster.",
    "passwall": "Create a 5' wide, 8' high, 10' deep passage through stone, wood, or plaster.",
    "phantasmal terror": "Conjure forth the most terrifying horror from a victim's psyche.",
    "plane shift": "Transport self and up to 7 others to another plane of existence.",
    "plant door": "Step into a living tree and emerge from another tree at a distance.",
    "polymorph other": "Transform another creature into a new form, willingly or unwillingly.",
    "polymorph self": "Transform yourself into a different creature or form between SIZ 1-40.",
    "power word – stun": "Stun a weakened creature instantly with a single uttered command.",
    "power word stun": "Stun a weakened creature instantly with a single uttered command.",
    "prayer": "Bolster allies (+5% skills, +1 damage) and hinder foes. Can stack with Chant.",
    "produce fire": "Conjure a roaring flame for attack or illumination in 120' area for 1 Round.",
    "quench fire": "Extinguish natural or magical flames in 120' area for 1 Round.",
    "produce fire (quench fire)": "Ignite intense magical flames or extinguish them in 120' area.",
    "protection from lightning": "Create a field absorbing 2 electrical damage per Intensity.",
    "quest": "Impose a binding geas compelling a creature to perform a specific service.",
    "raise dead": "Restore life to a creature that died within 24 hours per Intensity.",
    "slay living": "Channel deadly energy to kill a creature that fails Willpower instantly.",
    "raise dead (slay living)": "Return a creature to life or strike it down with fatal magic.",
    "regenerate": "Touch one creature to regrow a dismembered Hit Location at 1 HP per 10 minutes.",
    "wither": "Cause the touched Hit Location to shrivel, becoming useless and eventually falling off.",
    "regenerate (wither)": "Regrow damaged limbs or magically decay them.",
    "repel insects": "Create a protective barrier that keeps insects at bay.",
    "restoration": "Restore life force previously drained by Energy Drain or similar effects.",
    "rock to mud": "Liquefy non-magical, natural stone into thick, clinging mud.",
    "mud to rock": "Harden mud into soft stone such as limestone or sandstone instantly.",
    "rock to mud (mud to rock)": "Transform non-magical natural stone into mud or mud into stone.",
    "shadow door": "Create an illusion of a door opening into a 10' square room.",
    "shadow magic": "Cast a quasi-real version of a Rank 1 or 2 Arcane Evocation spell.",
    "shadow monsters": "Extract substance from Plane of Shadow to create quasi-real illusions of creatures.",
    "stone shape": "Reshape touched stone into any desired form, 1 cubic foot per Intensity.",
    "speak with plants": "Communicate with all living vegetation within Area of Effect.",
    "sphere of invulnerability, lesser": "Create an immobile sphere blocking all Rank 1 spells.",
    "lesser sphere of invulnerability": "Create an immobile sphere blocking all Rank 1 spells.",
    "sticks to snakes": "Transform 1d4+1/Intensity sticks into venomous snakes.",
    "snakes to sticks": "Turn serpents back into harmless sticks for its Duration.",
    "sticks to snakes (snakes to sticks)": "Animate sticks as venomous snakes or return snakes to inert wood.",
    "stone tell": "Stone becomes capable of answering questions about its immediate surroundings.",
    "summon shadow": "Call a dangerous undead shadow to serve you temporarily.",
    "telekinesis": "Move objects or creatures at a distance using pure will.",
    "teleport": "Instantly transport yourself any distance within the same plane of existence.",
    "true sight": "Perceive reality clearly, seeing through illusions, invisibility, magical concealments.",
    "false sight": "Cloud a creature's perceptions with a twisted, deceptive version of reality.",
    "true sight (false sight)": "Reveal all hidden truths or cloak them with deceptive reality.",
    "wall of fire": "Conjure a wall or circle of blazing flame, chosen at time of casting.",
    "wall of force": "Conjure an invisible wall of magical force within 100' of you.",
    "wall of ice": "Conjure a large mass of ice in form of a wall, dome, or falling sheet.",
    "wizard sight": "Create a small invisible magical 'eye' that you can see through.",

    // === Rank 4 Spells ===
    "animal summoning ii": "Call more potent animals of a chosen type to come and aid you.",
    "animate object": "Temporarily bring inanimate objects to life to move and obey simple commands.",
    "anti-animal shell": "Create a protective barrier normal animals cannot cross (including humans, giants, dragons).",
    "anti-magic shell": "Raise an invisible barrier blocking most magical effects, moves with caster.",
    "antimagic shell": "Raise an invisible barrier blocking most magical effects, moves with caster.",
    "big grasping hand": "Conjure a massive hand of force that can grasp, push, or hold creatures.",
    "blade barrier": "Summon a whirling wall of blades doing 1d8 damage to 1d4+2 random Hit Locations.",
    "chain lightning": "Hurl a bolt of lightning that arcs from one target to others, diminishing with each.",
    "conjure animals": "Summon a group of animals to fight, scout, or otherwise aid you.",
    "conjure fire elemental": "Summon a powerful fire elemental to serve. No element portion required.",
    "dismiss fire elemental": "Banish a conjured fire elemental back to its native plane.",
    "conjure fire elemental (dismiss fire elemental)": "Summon a fire elemental or dismiss one to its home plane.",
    "control undead": "Command up to 6 undead to obey or hesitate, depending on Undead Intensity.",
    "control weather": "Shift local weather over time across a large area.",
    "death spell": "Instantly slay multiple weaker creatures of SIZ 40 or less within Area of Effect.",
    "demi-shadow magic": "Create quasi-real versions of Rank 3 Arcane Evocation spells.",
    "demi-shadow monsters": "Summon shadowy creatures that are partly real and can harm foes.",
    "disintegrate": "A thin green ray disintegrates the first object or creature struck if it fails to resist.",
    "duo-dimension": "Flatten yourself into two dimensions, becoming extremely thin and hard to hit.",
    "enchant item": "Permanently invest an item with magical power after lengthy preparation.",
    "etherealness, lesser": "Partially shift into the Ethereal Plane for limited passage through matter.",
    "lesser etherealness": "Partially shift into the Ethereal Plane for limited passage through matter.",
    "find the path": "Reveal the most direct, safe route to a specific destination.",
    "lose the path": "Cloud a creature's sense of direction, causing them to stray from their route.",
    "find the path (lose the path)": "Uncover the surest way to a destination or mislead others away.",
    "fireball, delayed": "Create a powerful fireball that detonates after a chosen delay.",
    "delayed fireball": "Create a powerful fireball that detonates after a chosen delay.",
    "flame seeds": "Turn acorns or berries into grenades or delayed incendiary devices.",
    "flesh to stone": "Transform a living creature into solid, inert stone.",
    "stone to flesh": "Restore stone that was once flesh back into living tissue.",
    "flesh to stone (stone to flesh)": "Petrify a living creature or reverse petrification and restore life.",
    "forbiddance": "Consecrate an area, sealing it from teleportation, ethereal travel, or plane shifting.",
    "geas": "Impose a long-term magical compulsion to follow or avoid a specific course of action.",
    "heal": "Cure all disease and injury with a single touch. Recovery depends on Intensity.",
    "harm": "Inflict deep magical injury to a single Hit Location.",
    "heal (harm)": "Fully restore a creature to health or ravage it with devastating negative energy.",
    "heroes feast": "Conjure a grand banquet that nourishes and grants powerful protective boons.",
    "heroes' feast": "Conjure a grand banquet that nourishes and grants powerful protective boons.",
    "illusion, permanent": "Create an illusion that endures indefinitely until dispelled.",
    "permanent illusion": "Create an illusion that endures indefinitely until dispelled.",
    "invisible stalker": "Summon an invisible stalker from the Elemental Plane of Air for a task.",
    "live oak": "Awaken a great tree into a mobile guardian that obeys your directions.",
    "major creation": "Conjure complex, durable nonliving objects from magical substance.",
    "monster summoning, greater": "Call powerful extraplanar monsters to serve you for a limited time.",
    "greater monster summoning": "Call powerful extraplanar monsters to serve you for a limited time.",
    "pass plant": "Step into one living tree and emerge from another at no more than 1,800' away.",
    "phase door": "Create an invisible passage through solid matter that only you or designated creatures can use.",
    "power word – blind": "Blind a weakened creature instantly with a single spoken word of power.",
    "power word blind": "Blind a weakened creature instantly with a single spoken word of power.",
    "prismatic spray": "Unleash a cone of seven multicolored beams, each with a different deadly effect.",
    "prismatic wall": "Raise a shimmering wall of seven layered colors, each layer bearing a distinct effect.",
    "project image": "Create a semi-real duplicate of yourself at a distance to cast spells and mislead foes.",
    "reincarnation": "Return a dead creature to life in a new, often different body.",
    "shadow walk": "Travel rapidly along the border of the Plane of Shadow, crossing great distances.",
    "speak with monsters": "Communicate with intelligent or monstrous creatures capable of communication.",
    "sphere of invulnerability, greater": "Create a protective dome blocking most spells of moderate power or less.",
    "greater sphere of invulnerability": "Create a protective dome blocking most spells of moderate power or less.",
    "teleport, precise": "Teleport with exceptional accuracy within your plane, greatly reducing mishap risk.",
    "precise teleport": "Teleport with exceptional accuracy within your plane, greatly reducing mishap risk.",
    "turn wood": "Twist or push away wooden objects and missiles in a broad area.",
    "wall of stone": "Conjure a stone wall that melds seamlessly with an existing stone surface.",
    "wall of thorns": "Create a durable wall of dense brush lined with sword-length thorns.",
    "water to dust": "Transform the designated area of liquid into a fine dust.",
    "dust to water": "Transform dust or dry powder into fresh water.",
    "water to dust (dust to water)": "Transform liquid into fine dust or conjure water from dust.",
    "weather summoning": "Call up or dismiss major weather patterns appropriate to the region.",
    "wish, limited": "Twist reality in a restricted but potent way, recreating many spell effects.",
    "limited wish": "Twist reality in a restricted but potent way, recreating many spell effects.",
    "word of recall": "Instantly transport yourself (and possibly others) to a sanctified location.",

    // === Rank 5 Spells ===
    "alter reality": "Like Wish, twist reality itself to emulate powerful spells or reshape circumstances.",
    "antipathy": "Imbue a location or object so creatures feel a powerful urge to avoid it.",
    "sympathy": "Imbue a location or object so creatures feel drawn toward it.",
    "antipathy/sympathy": "Repel creatures from a warded area or draw them irresistibly toward it.",
    "astral spell": "Enter the Astral Plane with up to five others (+1 per extra Intensity).",
    "big crushing fist": "Conjure a gigantic hand of force that squeezes, pummels, or grapples foes.",
    "changestaff": "Transform a specially prepared staff into a powerful living tree creature.",
    "conjure earth elemental": "Summon a mighty earth elemental to serve, with risks if control is lost.",
    "dismiss earth elemental": "Send a conjured earth elemental back to its native plane.",
    "conjure earth elemental (dismiss earth elemental)": "Summon an earth elemental or dismiss one to its home plane.",
    "creeping doom": "Call forth a vast carpet of swarming vermin that crawls and devours foes.",
    "disjunction": "Disrupt all spells being cast and ongoing magical effects within Area of Effect.",
    "earthquake": "Shake the ground with a devastating tremor that cracks surfaces and topples creatures.",
    "energy drain": "Impose two levels of permanent Fatigue loss on a victim who Fails Resistance Roll.",
    "etherealness, greater": "Become ethereal with one additional creature per Intensity beyond the first.",
    "greater etherealness": "Become ethereal with one additional creature per Intensity beyond the first.",
    "exaction": "Call forth a powerful entity from another realm (angel or minor demon level).",
    "finger of death": "Instantly stop a victim's heart, killing them outright. Affects only living creatures.",
    "fire storm": "Call down a devastating storm of fire that scorches a wide area.",
    "greater quench fire": "Extinguish intense magical and mundane fires across a broad region.",
    "fire storm (greater quench fire)": "Engulf an area in searing flames or extinguish even powerful fires.",
    "gate": "Open a portal to another plane, allowing travel or calling powerful beings through.",
    "holy word": "Utter a divine word that blasts Evil creatures, banishing, stunning, or weakening them.",
    "unholy word": "Speak a blasphemous word that devastates Good creatures in range.",
    "holy word (unholy word)": "Channel a sacred or profane word that devastates creatures of opposing Alignment.",
    "irresistible dance": "Compel a creature to dance uncontrollably, leaving it helpless.",
    "mass charm": "Charm a group of creatures at once so they view you as a trusted ally.",
    "maze": "Trap a creature in an extradimensional labyrinth until it finds its way out.",
    "metal to wood": "Transform metal objects into wood, rendering weapons and armor less effective.",
    "meteor shower": "Two micro-meteors per Intensity (max eight) streak from your outstretched hand.",
    "monster summoning, ultimate": "Call the most powerful extraplanar monsters available to fight briefly.",
    "ultimate monster summoning": "Call the most powerful extraplanar monsters available to fight briefly.",
    "part water": "Cleave a body of water aside, opening a dry path along its bed.",
    "permanency": "Make certain spell effects permanent at great personal cost.",
    "polymorph any object": "Transform creatures or objects into nearly any other form, sometimes permanently.",
    "power word – kill": "Slay a creature outright with a single, unstoppable word of power.",
    "power word kill": "Slay a creature outright with a single, unstoppable word of power.",
    "prismatic sphere": "Enclose yourself in a layered globe of seven shifting colors with deadly effects.",
    "resurrection": "Restore a long-dead creature to life, body and soul, under demanding conditions.",
    "destruction": "Unleash divine wrath that utterly annihilates a single creature.",
    "resurrection (destruction)": "Return a fallen soul to life or utterly obliterate a chosen enemy.",
    "succor": "Create a magical safeguard that later recalls you to safety or summons you to aid.",
    "sun ray": "Unleash a focused beam of brilliant holy sunlight that burns undead and light-vulnerable.",
    "symbol": "Inscribe a potent magical sigil that triggers powerful effects on those who approach.",
    "time stop": "Step outside normal time briefly, taking several actions while everything else is frozen.",
    "transport via plants": "Use large plants as portals, stepping into one and emerging from another far away.",
    "trap the soul": "Imprison a creature's very soul within a gem or similar receptacle.",
    "wind walk": "Transform the druid and up to 3 others into mist-like forms that drift swiftly.",
    "wish": "Invoke the mightiest mortal magic to reshape reality within broad but perilous limits."
  },

  // Cantrips (Rank 0)
  cantrips: {
    'Appraise': '1',
    'Avert': '1',
    'Babble': '1',
    'Beastcall': '1',
    'Beastcall (X)': '1',
    'Befuddle': '1',
    'Calculate': '1',
    'Calm': '1',
    'Calm Animal': '1',
    'Chill': '1',
    'Chill (Heat)': '1',
    'Heat': '1',
    'Cleanse': '1',
    'Cleanse (Dishevel)': '1',
    'Dishevel': '1',
    'Coordination': '1',
    'Deflect': '1',
    'Dry': '1',
    'Fanaticism': '1',
    'Fanaticism (Demoralize)': '1',
    'Demoralize': '1',
    'Frostbite': '1',
    'Glamour': '1',
    'Glamour (Repugnance)': '1',
    'Repugnance': '1',
    'Glue': '1',
    'Ignite': '1',
    'Ignite (Extinguish)': '1',
    'Extinguish': '1',
    'Incognito': '1',
    'Ironhand': '1',
    'Magic Tricks': '1',
    'Magnify': '1',
    'Might': '1',
    'Mimic': '1',
    'Mobility': '1',
    'Perfume': '1',
    'Pet': '1',
    'Polish': '1',
    'Preserve': '1',
    'Protection': '1',
    'Repair': '1',
    'Spiritshield': '1',
    'Tidy': '1',
    'Tune': '1',
    'Voice': '1'
  },

  // Rank 1 Spells
  rank1: {
    'Acid Arrow': '1/Intensity',
    'Affect Normal Fires': '1/Intensity',
    'Alarm': '1/Intensity',
    'Animal Friendship': '1/Intensity',
    'Armor': '3, +1/add\'l. Intensity',
    'Audible Illusion': '1/Intensity',
    'Barkskin': '1/Intensity',
    'Bind': '1/Intensity',
    'Bless': '1/Intensity',
    'Bless (Curse)': '1/Intensity',
    'Curse': '1/Intensity',
    'Blindness': '3, +1/add\'l. Intensity',
    'Blur': '3, +1/add\'l. Intensity',
    'Ceremony': '1',
    'Change Appearance': '1/Intensity',
    'Charm Being': '3/Intensity',
    'Chill Touch': '1/Intensity',
    'Color Cascade': '1/Intensity',
    'Combine': '1',
    'Command': '3',
    'Create Water': '1/Intensity',
    'Create Water (Destroy Water)': '1/Intensity',
    'Destroy Water': '1/Intensity',
    'Cure Fatigue': '1',
    'Cure Fatigue (Cause Fatigue)': '1',
    'Cause Fatigue': '1',
    'Cure Minor Wounds': '3',
    'Cure Minor Wounds (Cause Minor Wounds)': '3',
    'Cause Minor Wounds': '3',
    'Deafness': '3, +1/add\'l. Intensity',
    'Detect Charm': '1/Intensity',
    'Detect Charm (Hide Charm)': '1/Intensity',
    'Hide Charm': '1/Intensity',
    'Detect Evil': '1/Intensity',
    'Detect Evil (Detect Good)': '1/Intensity',
    'Detect Good': '1/Intensity',
    'Detect Illusion': '1/Intensity',
    'Detect Magic': '1/Intensity',
    'Detect Poison': '1/Intensity',
    'Detect Snares and Pits': '1/Intensity',
    'Detect Undead': '1/Intensity',
    'Disk of Burden': '1/Intensity',
    'Dust Devil': '3, +1/add\'l. Intensity',
    'Endure Heat/Cold': '1/Intensity',
    'Enlarge': '3, +1/add\'l. Intensity',
    'Enlarge (Reduce)': '3, +1/add\'l. Intensity',
    'Reduce': '3, +1/add\'l. Intensity',
    'Entangle': '3, +1/add\'l. Intensity',
    'Erase Writing': '1/Intensity',
    'Faerie Fire': '3, +1/add\'l. Intensity',
    'Faerie Lights': '1/Intensity',
    'Familiar': '3/Intensity, +1 EXP',
    'Feather Fall': '1/Intensity',
    'Find Traps': '3, +1/add\'l. Intensity',
    'Flame Blade': '1/Intensity',
    'Flaming Hands': '1/Intensity',
    'Friendship': '3, +1/add\'l. Intensity',
    'Goodberry': '1/Intensity',
    'Goodberry (Badberry)': '1/Intensity',
    'Badberry': '1/Intensity',
    'Grease': '1/Intensity',
    'Hypnotism': '1/Intensity',
    'Identify': '1/Intensity',
    'Illusion, Lesser': '1/Intensity',
    'Lesser Illusion': '1/Intensity',
    'Invisibility, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Invisibility': '3, +1/add\'l. Intensity',
    'Invisibility to Animals': '3, +1/add\'l. Intensity',
    'Invisibility to Undead': '3',
    'Jump': '1/Intensity',
    'Know Languages': '1/Intensity',
    'Know Languages (Confuse Languages)': '1/Intensity',
    'Confuse Languages': '1/Intensity',
    'Leonard\'s False Trap': '1',
    'Levitate': '1/Intensity',
    'Light': '1/Intensity',
    'Light (Darkness)': '1/Intensity',
    'Locate Animals or Plants': '1/Intensity',
    'Magic Aura': '1/Intensity',
    'Magic Missile': '3, +1/add\'l. Intensity',
    'Magical Stone': '1/Intensity',
    'Message': '1/Intensity',
    'Messenger': '1/Intensity',
    'Misdirection': '3',
    'Pass Without Trace': '1/Intensity',
    'Predict Weather': '1/Intensity',
    'Protection from Cantrips': '1/Intensity',
    'Protection from Evil': '1/Intensity',
    'Protection from Evil (Protection from Good)': '1/Intensity',
    'Protection from Good': '1/Intensity',
    'Purify Food and Drink': '1/Intensity',
    'Purify Food and Drink (Contaminate Food and Drink)': '1/Intensity',
    'Contaminate Food and Drink': '1/Intensity',
    'Read Magic': '1/Intensity',
    'Reflect Gaze': '1/Intensity',
    'Remove Fear': '1/Intensity',
    'Remove Fear (Cause Fear)': '1/Intensity',
    'Cause Fear': '1/Intensity',
    'Sanctuary': '1/Intensity',
    'Secure Portal': '1/Intensity',
    'Shield': '3, +1/add\'l. Intensity',
    'Shillelagh': '1/Intensity',
    'Shocking Touch': '1/Intensity',
    'Silence': '3, +1/add\'l. Intensity',
    'Sleep': '3, +1/add\'l. Intensity',
    'Slow Poison': '3, +1/add\'l. Intensity',
    'Spider Climb': '1/Intensity',
    'Uncontrollable Horrible Laughter': '1/Intensity',
    'Unseen Servant': '1/Intensity',
    'Ventriloquism': '1/Intensity'
  },

  // Rank 2 Spells
  rank2: {
    'Aid': '3, +1/add\'l. Intensity',
    'Alter Self': '3, +1/add\'l. Intensity',
    'Augury': '1/Intensity',
    'Blink': '3, +1/add\'l. Intensity',
    'Breathe Water': '3, +1/add\'l. Intensity',
    'Breathe Water (Breathe Air)': '3, +1/add\'l. Intensity',
    'Breathe Air': '3, +1/add\'l. Intensity',
    'Call Lightning': '3, +1/add\'l. Intensity',
    'Chant': '3, +1/add\'l. Intensity',
    'Charm Being or Mammal': '3/Intensity',
    'Clairaudience': 'See description',
    'Clairvoyance': 'See description',
    'Clairaudience/Clairvoyance': 'See description',
    'Commune with Nature': '3, +1/add\'l. Intensity',
    'Continual Light': '3',
    'Continual Light (Continual Darkness)': '3',
    'Continual Darkness': '3',
    'Create Food and Water': '3, +1/add\'l. Intensity',
    'Cure Blindness or Deafness': '3',
    'Cure Blindness or Deafness (Cause Blindness or Deafness)': '3',
    'Cause Blindness or Deafness': '3',
    'Cure Disease': '1/Intensity',
    'Cure Disease (Cause Disease)': '1/Intensity',
    'Cause Disease': '1/Intensity',
    'Cure Serious Wounds': '3',
    'Cure Serious Wounds (Cause Serious Wounds)': '3',
    'Cause Serious Wounds': '3',
    'Darkness': '1/Intensity',
    'Darkvision': '1/Intensity',
    'Detect Invisibility': '1/Intensity',
    'Dispel Magic': '1/Intensity',
    'Enfeeblement': '3, +1/add\'l. Intensity',
    'Feign Death': '3, +1/add\'l. Intensity',
    'Fireball': '3, +1/add\'l. Intensity',
    'Fire Trap': '3, +1/add\'l. Intensity',
    'Flame Arrow': '3, +1/add\'l. Intensity',
    'Flame Strike': '3, +1/add\'l. Intensity',
    'Flame Walk': '3, +1/add\'l. Intensity',
    'Fly': '3, +1/add\'l. Intensity',
    'Forget': '1/Intensity',
    'Gust of Wind': '3, +1/add\'l. Intensity',
    'Haste': '3, +1/add\'l. Intensity',
    'Heat Metal': '3, +1/add\'l. Intensity',
    'Heat Metal (Chill Metal)': '3, +1/add\'l. Intensity',
    'Chill Metal': '3, +1/add\'l. Intensity',
    'Hold Animal': '3, +1/add\'l. Intensity',
    'Hold Person': '3, +1/add\'l. Intensity',
    'Hold Undead': '3, +1/add\'l. Intensity',
    'Illusion, Greater': '1/Intensity',
    'Greater Illusion': '1/Intensity',
    'Invisibility (10ft)': '3, +1/add\'l. Intensity',
    'Invisibility 10\' Radius': '3, +1/add\'l. Intensity',
    'Know Passions': '1/Intensity',
    'Know Passions (Obscure Passions)': '1/Intensity',
    'Obscure Passions': '1/Intensity',
    'Leonard\'s Tiny Magic Hut': '3, +1/add\'l. Intensity',
    'Lightning Bolt': '3, +1/add\'l. Intensity',
    'Locate Object': '1/Intensity',
    'Locate Object (Obscure Object)': '1/Intensity',
    'Obscure Object': '1/Intensity',
    'Mage Lock': '3, +1/add\'l. Intensity',
    'Magic Mouth': '1/Intensity',
    'Minute Meteors': '3, +1/add\'l. Intensity',
    'Mirror Images': '1/Intensity',
    'Monster Summoning, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Monster Summoning': '3, +1/add\'l. Intensity',
    'Obscurement': '1/Intensity',
    'Plant Growth': '1/Intensity',
    'Produce Flame': '3, +1/add\'l. Intensity',
    'Protection from Cold': '3, +1/add\'l. Intensity',
    'Protection from Evil 10\' Radius': '3, +1/add\'l. Intensity',
    'Protection from Evil 10\' Radius (Protection from Good 10\' Radius)': '3, +1/add\'l. Intensity',
    'Protection from Good 10\' Radius': '3, +1/add\'l. Intensity',
    'Protection from Fire': '3, +1/add\'l. Intensity',
    'Protection from Mundane Missiles': '3, +1/add\'l. Intensity',
    'Pyrotechnics': '3, +1/add\'l. Intensity',
    'Read Thoughts': '1/Intensity',
    'Remove Curse': '3, +1/add\'l. Intensity',
    'Remove Curse (Bestow Curse)': '3, +1/add\'l. Intensity',
    'Bestow Curse': '3, +1/add\'l. Intensity',
    'Remove Paralysis': '3, +1/add\'l. Intensity',
    'Scare': '3, +1/add\'l. Intensity',
    'Sigil of Warding': '1/Intensity',
    'Slow': '3/Intensity',
    'Snake Charm': '1/Intensity',
    'Snare': '3',
    'Speak with Animals': '1/Intensity',
    'Speak with Dead': '1/Intensity',
    'Spectral Hand': '1/Intensity',
    'Spiritual Hammer': '3, +1/add\'l. Intensity',
    'Stinking Cloud': '3, +1/add\'l. Intensity',
    'Strength': '3, +1/add\'l. Intensity',
    'Suggestion': '1/Intensity',
    'Summon Insects': '1/Intensity',
    'Tongues': '1/Intensity',
    'Tongues (Confuse Tongues)': '1/Intensity',
    'Confuse Tongues': '1/Intensity',
    'Tree': '1/Intensity',
    'Trip': '1/Intensity',
    'Unlock': '1/Intensity',
    'Unlock (Lock)': '1/Intensity',
    'Lock': '1/Intensity',
    'Vampiric Touch': '3',
    'Warp Wood': '1/Intensity',
    'Warp Wood (Straighten Wood)': '1/Intensity',
    'Straighten Wood': '1/Intensity',
    'Water Walk': '3, +1/add\'l. Intensity',
    'Web': '3, +1/add\'l. Intensity'
  },

  // Rank 3 Spells
  rank3: {
    'Aerial Servant': '3/Intensity',
    'Air Walk': '3, +1/add\'l. Intensity',
    'Animal Growth': '3, +1/add\'l. Intensity',
    'Animal Growth (Shrink Animal)': '3, +1/add\'l. Intensity',
    'Shrink Animal': '3, +1/add\'l. Intensity',
    'Animal Summoning I': '1/Intensity',
    'Animate Dead': '3, +1/add\'l. Intensity (+1 EXP)',
    'Anti-Plant Shell': '3, +1/add\'l. Intensity',
    'Atonement': '3, plus see description',
    'Big Interposing Hand': '3, +1/add\'l. Intensity',
    'Call Woodland Beings': '3, +1/add\'l. Intensity',
    'Charm Monster': '3/Intensity',
    'Cloud Kill': '3, +1/add\'l. Intensity',
    'Cloudkill': '3, +1/add\'l. Intensity',
    'Commune': '3, +1/add\'l. Intensity, +1 EXP',
    'Cone of Cold': '3, +1/add\'l. Intensity',
    'Confusion': '3, +1/add\'l. Intensity',
    'Conjure Elemental': '3, +1/add\'l. Intensity',
    'Control Temperature 10\' Radius': '3, +1/add\'l. Intensity',
    'Control Winds': '1/Intensity',
    'Cure Major Wounds': '3, +1/add\'l. Intensity',
    'Cure Major Wounds (Cause Major Wounds)': '3, +1/add\'l. Intensity',
    'Cause Major Wounds': '3, +1/add\'l. Intensity',
    'Detect Lie': '1/Intensity',
    'Detect Lie (Undetectable Lie)': '1/Intensity',
    'Undetectable Lie': '1/Intensity',
    'Dimension Door': '3, +1/add\'l. Intensity',
    'Dispel Evil': '3, +1/add\'l. Intensity',
    'Dispel Evil (Banish Good)': '3, +1/add\'l. Intensity',
    'Banish Good': '3, +1/add\'l. Intensity',
    'Divination': '3, +1/add\'l. Intensity',
    'Domination': '3/Intensity',
    'Enchant Weapon': '3, +1/add\'l. Intensity',
    'Exorcism': '3, +1/add\'l. Intensity',
    'Fear': '3, +1/add\'l. Intensity',
    'Feeblemind': '3, +1/add\'l. Intensity',
    'Free Action': '3, +1/add\'l. Intensity',
    'Fumble': '3, +1/add\'l. Intensity',
    'Hallucinatory Forest': '3/Intensity',
    'Hail/Ice Storm': '3, +1/add\'l. Intensity',
    'Ice Storm': '3, +1/add\'l. Intensity',
    'Heat/Cold Shield': '3, +1/add\'l. Intensity',
    'Hold Plant': '3, +1/add\'l. Intensity',
    'Hold Monster': '3, +1/add\'l. Intensity',
    'Illusionary Terrain': '3, +1/add\'l. Intensity',
    'Illusion, Advanced': '3, +1/add\'l. Intensity',
    'Advanced Illusion': '3, +1/add\'l. Intensity',
    'Insect Plague': '3, +1/add\'l. Intensity',
    'Invisibility, Greater': '3, +1/add\'l. Intensity',
    'Greater Invisibility': '3, +1/add\'l. Intensity',
    'Legend Lore': '3, +1/hour',
    'Leonard\'s Secure Cottage': '3, +1/add\'l. Intensity',
    'Lesser Creation': '3, +1/add\'l. Intensity',
    'Lower Water': '3, +1/add\'l. Intensity',
    'Lower Water (Raise Water)': '3, +1/add\'l. Intensity',
    'Raise Water': '3, +1/add\'l. Intensity',
    'Monster Summoning': '3, +1/add\'l. Intensity',
    'Neutralize Poison': '3, +1/add\'l. Intensity',
    'Neutralize Poison (Inflict Poison)': '3, +1/add\'l. Intensity',
    'Inflict Poison': '3, +1/add\'l. Intensity',
    'Pass Wall': '3, +1/add\'l. Intensity',
    'Passwall': '3, +1/add\'l. Intensity',
    'Phantasmal Terror': '3, +1/add\'l. Intensity',
    'Plane Shift': '3, +1/add\'l. Intensity',
    'Plant Door': '3, +1/add\'l. Intensity',
    'Polymorph Other': '3/Intensity',
    'Polymorph Self': '3, +1/add\'l. Intensity',
    'Power Word – Stun': '3, +1/add\'l. Intensity',
    'Power Word Stun': '3, +1/add\'l. Intensity',
    'Prayer': '3, +1/add\'l. Intensity',
    'Produce Fire': '3, +1/add\'l. Intensity',
    'Produce Fire (Quench Fire)': '3, +1/add\'l. Intensity',
    'Quench Fire': '3, +1/add\'l. Intensity',
    'Protection from Lightning': '3, +1/add\'l. Intensity',
    'Quest': '3, +1 EXP',
    'Raise Dead': '3, +1/add\'l. Intensity, +1 EXP',
    'Raise Dead (Slay Living)': '3, +1/add\'l. Intensity, +1 EXP',
    'Slay Living': '3, +1/add\'l. Intensity, +1 EXP',
    'Regenerate': '3/Intensity',
    'Regenerate (Wither)': '3/Intensity',
    'Wither': '3/Intensity',
    'Repel Insects': '3, +1/add\'l. Intensity',
    'Restoration': '3, +1/add\'l. Intensity',
    'Rock to Mud': '3, +1/add\'l. Intensity',
    'Rock to Mud (Mud to Rock)': '3, +1/add\'l. Intensity',
    'Mud to Rock': '3, +1/add\'l. Intensity',
    'Shadow Door': '3, +1/add\'l. Intensity',
    'Shadow Magic': 'See description',
    'Shadow Monsters': '3, +1/add\'l. Intensity',
    'Stone Shape': '1/Intensity',
    'Speak with Plants': '1/Intensity',
    'Sphere of Invulnerability, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Sphere of Invulnerability': '3, +1/add\'l. Intensity',
    'Sticks to Snakes': '3, +1/add\'l. Intensity',
    'Sticks to Snakes (Snakes to Sticks)': '3, +1/add\'l. Intensity',
    'Snakes to Sticks': '3, +1/add\'l. Intensity',
    'Stone Tell': '3',
    'Summon Shadow': '3/Intensity',
    'Telekinesis': '3, +1/add\'l. Intensity',
    'Teleport': '3, +1/add\'l. Intensity',
    'True Sight': '3, +1/add\'l. Intensity',
    'True Sight (False Sight)': '3, +1/add\'l. Intensity',
    'False Sight': '3, +1/add\'l. Intensity',
    'Wall of Fire': '3, +1/add\'l. Intensity',
    'Wall of Force': '3, +1/add\'l. Intensity',
    'Wall of Ice': '3, +1/add\'l. Intensity',
    'Wizard Sight': '1/Intensity'
  },

  // Rank 4 Spells
  rank4: {
    'Animal Summoning II': '3, +1/add\'l. Intensity',
    'Animate Object': '1/Intensity',
    'Anti-Animal Shell': '3, +1/add\'l. Intensity',
    'Anti-Magic Shell': '3, +1/add\'l. Intensity',
    'Antimagic Shell': '3, +1/add\'l. Intensity',
    'Big Grasping Hand': '3, +1/add\'l. Intensity',
    'Blade Barrier': '3, +1/add\'l. Intensity',
    'Chain Lightning': '3, +1/add\'l. Intensity',
    'Conjure Animals': '3, +1/add\'l. Intensity',
    'Conjure Fire Elemental': '3, +1/add\'l. Intensity',
    'Conjure Fire Elemental (Dismiss Fire Elemental)': '3, +1/add\'l. Intensity',
    'Dismiss Fire Elemental': '3, +1/add\'l. Intensity',
    'Control Undead': '3/Intensity',
    'Control Weather': '3/Intensity',
    'Death Spell': '3, +1/add\'l. Intensity',
    'Demi-Shadow Magic': '3, +1/add\'l. Intensity',
    'Demi-Shadow Monsters': '3, +1/add\'l. Intensity',
    'Disintegrate': '3/Intensity, +1 EXP',
    'Duo-Dimension': '3, +1/add\'l. Intensity',
    'Enchant Item': '3, +See description',
    'Etherealness, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Etherealness': '3, +1/add\'l. Intensity',
    'Find the Path': '3, +1/add\'l. Intensity',
    'Find the Path (Lose the Path)': '3, +1/add\'l. Intensity',
    'Lose the Path': '3, +1/add\'l. Intensity',
    'Fireball, Delayed': '3, +1/add\'l. Intensity',
    'Delayed Fireball': '3, +1/add\'l. Intensity',
    'Flame Seeds': '3, +1/add\'l. Intensity',
    'Flesh to Stone': '3/Intensity',
    'Flesh to Stone (Stone to Flesh)': '3/Intensity',
    'Stone to Flesh': '3/Intensity',
    'Forbiddance': '3, +1/add\'l. Intensity',
    'Geas': '3, +1 EXP',
    'Heal': '3, +1/add\'l. Intensity',
    'Heal (Harm)': '3, +1/add\'l. Intensity',
    'Harm': '3, +1/add\'l. Intensity',
    'Heroes Feast': '3, +1/add\'l. Intensity',
    'Heroes\' Feast': '3, +1/add\'l. Intensity',
    'Illusion, Permanent': '3, +1/add\'l. Intensity',
    'Permanent Illusion': '3, +1/add\'l. Intensity',
    'Invisible Stalker': '3, +1 EXP, plus see description',
    'Live Oak': '3, +1/add\'l. Intensity',
    'Major Creation': '3, +1/add\'l. Intensity',
    'Monster Summoning, Greater': '3, +1/add\'l. Intensity',
    'Greater Monster Summoning': '3, +1/add\'l. Intensity',
    'Pass Plant': '3, +1/add\'l. Intensity',
    'Phase Door': '3, +1/add\'l. Intensity',
    'Power Word – Blind': '3, +1/add\'l. Intensity',
    'Power Word Blind': '3, +1/add\'l. Intensity',
    'Prismatic Spray': '3',
    'Prismatic Wall': '3/Intensity',
    'Project Image': '3, +1/add\'l. Intensity',
    'Reincarnation': '3, +1/add\'l. Intensity, +1 EXP',
    'Shadow Walk': '3, +1/add\'l. Intensity',
    'Speak with Monsters': '3, +1/add\'l. Intensity',
    'Sphere of Invulnerability, Greater': '3, +1/add\'l. Intensity',
    'Greater Sphere of Invulnerability': '3, +1/add\'l. Intensity',
    'Teleport, Precise': '3, +1/add\'l. Intensity',
    'Precise Teleport': '3, +1/add\'l. Intensity',
    'Turn Wood': '3, +1/add\'l. Intensity',
    'Wall of Stone': '3, +1/add\'l. Intensity',
    'Wall of Thorns': '3, +1/add\'l. Intensity',
    'Water to Dust': '3, +1/add\'l. Intensity',
    'Water to Dust (Dust to Water)': '3, +1/add\'l. Intensity',
    'Dust to Water': '3, +1/add\'l. Intensity',
    'Weather Summoning': '3',
    'Wish, Limited': '3, +1 or more EXP',
    'Limited Wish': '3, +1 or more EXP',
    'Word of Recall': '3, +1/add\'l. Intensity'
  },

  // Rank 5 Spells
  rank5: {
    'Alter Reality': '3, +1 or more EXP',
    'Antipathy/Sympathy': '3, +1/add\'l. Intensity',
    'Antipathy': '3, +1/add\'l. Intensity',
    'Sympathy': '3, +1/add\'l. Intensity',
    'Astral Spell': '3, +1/add\'l. Intensity',
    'Big Crushing Fist': '3, +1/add\'l. Intensity',
    'Changestaff': '3, +1 EXP',
    'Conjure Earth Elemental': '3, +1/add\'l. Intensity',
    'Conjure Earth Elemental (Dismiss Earth Elemental)': '3, +1/add\'l. Intensity',
    'Dismiss Earth Elemental': '3, +1/add\'l. Intensity',
    'Creeping Doom': '3, +1/add\'l. Intensity',
    'Disjunction': '3, +1/add\'l. Intensity, +1 EXP',
    'Earthquake': '3, +1/add\'l. Intensity',
    'Energy Drain': '3',
    'Etherealness, Greater': '3, +1/add\'l. Intensity',
    'Greater Etherealness': '3, +1/add\'l. Intensity',
    'Exaction': '3, +1 EXP',
    'Finger of Death': '3, +1/add\'l. Intensity, +3 EXP',
    'Fire Storm': '3, +1/add\'l. Intensity',
    'Fire Storm (Greater Quench Fire)': '3, +1/add\'l. Intensity',
    'Greater Quench Fire': '3, +1/add\'l. Intensity',
    'Gate': '3/Intensity, + See description',
    'Holy Word': '3, +1 EXP',
    'Holy Word (Unholy Word)': '3, +1 EXP',
    'Unholy Word': '3, +1 EXP',
    'Irresistible Dance': '3',
    'Mass Charm': '3/Intensity, +1 EXP',
    'Maze': '3, +1/add\'l. Intensity',
    'Metal to Wood': '3, +1/add\'l. Intensity, +1 EXP',
    'Meteor Shower': '3/Intensity',
    'Monster Summoning, Ultimate': '3, +1/add\'l. Intensity',
    'Ultimate Monster Summoning': '3, +1/add\'l. Intensity',
    'Part Water': '3, +1/add\'l. Intensity',
    'Permanency': '3, +1 EXP',
    'Polymorph any Object': '3/Intensity',
    'Power Word – Kill': '3/Intensity, +1 EXP',
    'Power Word Kill': '3/Intensity, +1 EXP',
    'Prismatic Sphere': '3/Intensity',
    'Resurrection': '3, +1/add\'l. Intensity, +2 EXP',
    'Resurrection (Destruction)': '3, +1/add\'l. Intensity, +2 EXP',
    'Destruction': '3, +1/add\'l. Intensity, +2 EXP',
    'Succor': '3, +1 EXP',
    'Sun Ray': '3/Intensity',
    'Symbol': '3, (Death +2 EXP)',
    'Time Stop': '3/Intensity, +1 EXP',
    'Transport via Plants': '3',
    'Trap the Soul': '3, +1 EXP',
    'Wind Walk': '3, +1/add\'l. Intensity',
    'Wish': '3, +1 or more EXP'
  },

  /**
   * Get the cost for a spell by name
   * Searches all ranks and returns the cost if found
   */
  getSpellCost(spellName, rank = null) {
    if (!spellName) return null;
    
    const normalizedName = spellName.trim();
    
    // If rank specified, search only that rank
    if (rank !== null) {
      const rankKey = rank === 0 ? 'cantrips' : `rank${rank}`;
      const rankData = this[rankKey];
      if (rankData) {
        // Try exact match first
        if (rankData[normalizedName]) {
          return rankData[normalizedName];
        }
        // Try case-insensitive match
        for (const [name, cost] of Object.entries(rankData)) {
          if (name.toLowerCase() === normalizedName.toLowerCase()) {
            return cost;
          }
        }
      }
      return null;
    }
    
    // Search all ranks
    const allRanks = ['cantrips', 'rank1', 'rank2', 'rank3', 'rank4', 'rank5'];
    for (const rankKey of allRanks) {
      const rankData = this[rankKey];
      // Try exact match first
      if (rankData[normalizedName]) {
        return rankData[normalizedName];
      }
      // Try case-insensitive match
      for (const [name, cost] of Object.entries(rankData)) {
        if (name.toLowerCase() === normalizedName.toLowerCase()) {
          return cost;
        }
      }
    }
    
    return null;
  },

  /**
   * Get rank number from rank key (for internal use)
   */
  getRankFromKey(rankKey) {
    if (rankKey === 'cantrips') return 0;
    const match = rankKey.match(/rank(\d)/);
    return match ? parseInt(match[1], 10) : null;
  },

  /**
   * Get the description for a spell by name
   * @param {string} spellName - The name of the spell
   * @returns {string|null} - The description or null if not found
   */
  getSpellDescription(spellName) {
    if (!spellName) return null;
    
    const normalizedName = spellName.trim().toLowerCase();
    
    // Try exact match first
    if (this.descriptions[normalizedName]) {
      return this.descriptions[normalizedName];
    }
    
    // Try with different variations
    // Remove parenthetical parts for partial match
    const baseNameMatch = normalizedName.match(/^([^(]+)/);
    if (baseNameMatch) {
      const baseName = baseNameMatch[1].trim();
      if (this.descriptions[baseName]) {
        return this.descriptions[baseName];
      }
    }
    
    return null;
  }
};

// Make available globally
window.SpellData = SpellData;
