/**
 * Spell Data for Mythras Classic Fantasy
 * Contains spell names and their magic point costs
 */

const SpellData = {
  // Cantrips (Rank 0)
  cantrips: {
    'Appraise': '1',
    'Avert': '1',
    'Babble': '1',
    'Beastcall': '1',
    'Beastcall (X)': '1',
    'Befuddle': '1',
    'Calculate': '1',
    'Calm': '1',
    'Calm Animal': '1',
    'Chill': '1',
    'Chill (Heat)': '1',
    'Heat': '1',
    'Cleanse': '1',
    'Cleanse (Dishevel)': '1',
    'Dishevel': '1',
    'Coordination': '1',
    'Deflect': '1',
    'Dry': '1',
    'Fanaticism': '1',
    'Fanaticism (Demoralize)': '1',
    'Demoralize': '1',
    'Frostbite': '1',
    'Glamour': '1',
    'Glamour (Repugnance)': '1',
    'Repugnance': '1',
    'Glue': '1',
    'Ignite': '1',
    'Ignite (Extinguish)': '1',
    'Extinguish': '1',
    'Incognito': '1',
    'Ironhand': '1',
    'Magic Tricks': '1',
    'Magnify': '1',
    'Might': '1',
    'Mimic': '1',
    'Mobility': '1',
    'Perfume': '1',
    'Pet': '1',
    'Polish': '1',
    'Preserve': '1',
    'Protection': '1',
    'Repair': '1',
    'Spiritshield': '1',
    'Tidy': '1',
    'Tune': '1',
    'Voice': '1'
  },

  // Rank 1 Spells
  rank1: {
    'Acid Arrow': '1/Intensity',
    'Affect Normal Fires': '1/Intensity',
    'Alarm': '1/Intensity',
    'Animal Friendship': '1/Intensity',
    'Armor': '3, +1/add\'l. Intensity',
    'Audible Illusion': '1/Intensity',
    'Barkskin': '1/Intensity',
    'Bind': '1/Intensity',
    'Bless': '1/Intensity',
    'Bless (Curse)': '1/Intensity',
    'Curse': '1/Intensity',
    'Blindness': '3, +1/add\'l. Intensity',
    'Blur': '3, +1/add\'l. Intensity',
    'Ceremony': '1',
    'Change Appearance': '1/Intensity',
    'Charm Being': '3/Intensity',
    'Chill Touch': '1/Intensity',
    'Color Cascade': '1/Intensity',
    'Combine': '1',
    'Command': '3',
    'Create Water': '1/Intensity',
    'Create Water (Destroy Water)': '1/Intensity',
    'Destroy Water': '1/Intensity',
    'Cure Fatigue': '1',
    'Cure Fatigue (Cause Fatigue)': '1',
    'Cause Fatigue': '1',
    'Cure Minor Wounds': '3',
    'Cure Minor Wounds (Cause Minor Wounds)': '3',
    'Cause Minor Wounds': '3',
    'Deafness': '3, +1/add\'l. Intensity',
    'Detect Charm': '1/Intensity',
    'Detect Charm (Hide Charm)': '1/Intensity',
    'Hide Charm': '1/Intensity',
    'Detect Evil': '1/Intensity',
    'Detect Evil (Detect Good)': '1/Intensity',
    'Detect Good': '1/Intensity',
    'Detect Illusion': '1/Intensity',
    'Detect Magic': '1/Intensity',
    'Detect Poison': '1/Intensity',
    'Detect Snares and Pits': '1/Intensity',
    'Detect Undead': '1/Intensity',
    'Disk of Burden': '1/Intensity',
    'Dust Devil': '3, +1/add\'l. Intensity',
    'Endure Heat/Cold': '1/Intensity',
    'Enlarge': '3, +1/add\'l. Intensity',
    'Enlarge (Reduce)': '3, +1/add\'l. Intensity',
    'Reduce': '3, +1/add\'l. Intensity',
    'Entangle': '3, +1/add\'l. Intensity',
    'Erase Writing': '1/Intensity',
    'Faerie Fire': '3, +1/add\'l. Intensity',
    'Faerie Lights': '1/Intensity',
    'Familiar': '3/Intensity, +1 EXP',
    'Feather Fall': '1/Intensity',
    'Find Traps': '3, +1/add\'l. Intensity',
    'Flame Blade': '1/Intensity',
    'Flaming Hands': '1/Intensity',
    'Friendship': '3, +1/add\'l. Intensity',
    'Goodberry': '1/Intensity',
    'Goodberry (Badberry)': '1/Intensity',
    'Badberry': '1/Intensity',
    'Grease': '1/Intensity',
    'Hypnotism': '1/Intensity',
    'Identify': '1/Intensity',
    'Illusion, Lesser': '1/Intensity',
    'Lesser Illusion': '1/Intensity',
    'Invisibility, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Invisibility': '3, +1/add\'l. Intensity',
    'Invisibility to Animals': '3, +1/add\'l. Intensity',
    'Invisibility to Undead': '3',
    'Jump': '1/Intensity',
    'Know Languages': '1/Intensity',
    'Know Languages (Confuse Languages)': '1/Intensity',
    'Confuse Languages': '1/Intensity',
    'Leonard\'s False Trap': '1',
    'Levitate': '1/Intensity',
    'Light': '1/Intensity',
    'Light (Darkness)': '1/Intensity',
    'Locate Animals or Plants': '1/Intensity',
    'Magic Aura': '1/Intensity',
    'Magic Missile': '3, +1/add\'l. Intensity',
    'Magical Stone': '1/Intensity',
    'Message': '1/Intensity',
    'Messenger': '1/Intensity',
    'Misdirection': '3',
    'Pass Without Trace': '1/Intensity',
    'Predict Weather': '1/Intensity',
    'Protection from Cantrips': '1/Intensity',
    'Protection from Evil': '1/Intensity',
    'Protection from Evil (Protection from Good)': '1/Intensity',
    'Protection from Good': '1/Intensity',
    'Purify Food and Drink': '1/Intensity',
    'Purify Food and Drink (Contaminate Food and Drink)': '1/Intensity',
    'Contaminate Food and Drink': '1/Intensity',
    'Read Magic': '1/Intensity',
    'Reflect Gaze': '1/Intensity',
    'Remove Fear': '1/Intensity',
    'Remove Fear (Cause Fear)': '1/Intensity',
    'Cause Fear': '1/Intensity',
    'Sanctuary': '1/Intensity',
    'Secure Portal': '1/Intensity',
    'Shield': '3, +1/add\'l. Intensity',
    'Shillelagh': '1/Intensity',
    'Shocking Touch': '1/Intensity',
    'Silence': '3, +1/add\'l. Intensity',
    'Sleep': '3, +1/add\'l. Intensity',
    'Slow Poison': '3, +1/add\'l. Intensity',
    'Spider Climb': '1/Intensity',
    'Uncontrollable Horrible Laughter': '1/Intensity',
    'Unseen Servant': '1/Intensity',
    'Ventriloquism': '1/Intensity'
  },

  // Rank 2 Spells
  rank2: {
    'Aid': '3, +1/add\'l. Intensity',
    'Alter Self': '3, +1/add\'l. Intensity',
    'Augury': '1/Intensity',
    'Blink': '3, +1/add\'l. Intensity',
    'Breathe Water': '3, +1/add\'l. Intensity',
    'Breathe Water (Breathe Air)': '3, +1/add\'l. Intensity',
    'Breathe Air': '3, +1/add\'l. Intensity',
    'Call Lightning': '3, +1/add\'l. Intensity',
    'Chant': '3, +1/add\'l. Intensity',
    'Charm Being or Mammal': '3/Intensity',
    'Clairaudience': 'See description',
    'Clairvoyance': 'See description',
    'Clairaudience/Clairvoyance': 'See description',
    'Commune with Nature': '3, +1/add\'l. Intensity',
    'Continual Light': '3',
    'Continual Light (Continual Darkness)': '3',
    'Continual Darkness': '3',
    'Create Food and Water': '3, +1/add\'l. Intensity',
    'Cure Blindness or Deafness': '3',
    'Cure Blindness or Deafness (Cause Blindness or Deafness)': '3',
    'Cause Blindness or Deafness': '3',
    'Cure Disease': '1/Intensity',
    'Cure Disease (Cause Disease)': '1/Intensity',
    'Cause Disease': '1/Intensity',
    'Cure Serious Wounds': '3',
    'Cure Serious Wounds (Cause Serious Wounds)': '3',
    'Cause Serious Wounds': '3',
    'Darkness': '1/Intensity',
    'Darkvision': '1/Intensity',
    'Detect Invisibility': '1/Intensity',
    'Dispel Magic': '1/Intensity',
    'Enfeeblement': '3, +1/add\'l. Intensity',
    'Feign Death': '3, +1/add\'l. Intensity',
    'Fireball': '3, +1/add\'l. Intensity',
    'Fire Trap': '3, +1/add\'l. Intensity',
    'Flame Arrow': '3, +1/add\'l. Intensity',
    'Flame Strike': '3, +1/add\'l. Intensity',
    'Flame Walk': '3, +1/add\'l. Intensity',
    'Fly': '3, +1/add\'l. Intensity',
    'Forget': '1/Intensity',
    'Gust of Wind': '3, +1/add\'l. Intensity',
    'Haste': '3, +1/add\'l. Intensity',
    'Heat Metal': '3, +1/add\'l. Intensity',
    'Heat Metal (Chill Metal)': '3, +1/add\'l. Intensity',
    'Chill Metal': '3, +1/add\'l. Intensity',
    'Hold Animal': '3, +1/add\'l. Intensity',
    'Hold Person': '3, +1/add\'l. Intensity',
    'Hold Undead': '3, +1/add\'l. Intensity',
    'Illusion, Greater': '1/Intensity',
    'Greater Illusion': '1/Intensity',
    'Invisibility (10ft)': '3, +1/add\'l. Intensity',
    'Invisibility 10\' Radius': '3, +1/add\'l. Intensity',
    'Know Passions': '1/Intensity',
    'Know Passions (Obscure Passions)': '1/Intensity',
    'Obscure Passions': '1/Intensity',
    'Leonard\'s Tiny Magic Hut': '3, +1/add\'l. Intensity',
    'Lightning Bolt': '3, +1/add\'l. Intensity',
    'Locate Object': '1/Intensity',
    'Locate Object (Obscure Object)': '1/Intensity',
    'Obscure Object': '1/Intensity',
    'Mage Lock': '3, +1/add\'l. Intensity',
    'Magic Mouth': '1/Intensity',
    'Minute Meteors': '3, +1/add\'l. Intensity',
    'Mirror Images': '1/Intensity',
    'Monster Summoning, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Monster Summoning': '3, +1/add\'l. Intensity',
    'Obscurement': '1/Intensity',
    'Plant Growth': '1/Intensity',
    'Produce Flame': '3, +1/add\'l. Intensity',
    'Protection from Cold': '3, +1/add\'l. Intensity',
    'Protection from Evil 10\' Radius': '3, +1/add\'l. Intensity',
    'Protection from Evil 10\' Radius (Protection from Good 10\' Radius)': '3, +1/add\'l. Intensity',
    'Protection from Good 10\' Radius': '3, +1/add\'l. Intensity',
    'Protection from Fire': '3, +1/add\'l. Intensity',
    'Protection from Mundane Missiles': '3, +1/add\'l. Intensity',
    'Pyrotechnics': '3, +1/add\'l. Intensity',
    'Read Thoughts': '1/Intensity',
    'Remove Curse': '3, +1/add\'l. Intensity',
    'Remove Curse (Bestow Curse)': '3, +1/add\'l. Intensity',
    'Bestow Curse': '3, +1/add\'l. Intensity',
    'Remove Paralysis': '3, +1/add\'l. Intensity',
    'Scare': '3, +1/add\'l. Intensity',
    'Sigil of Warding': '1/Intensity',
    'Slow': '3/Intensity',
    'Snake Charm': '1/Intensity',
    'Snare': '3',
    'Speak with Animals': '1/Intensity',
    'Speak with Dead': '1/Intensity',
    'Spectral Hand': '1/Intensity',
    'Spiritual Hammer': '3, +1/add\'l. Intensity',
    'Stinking Cloud': '3, +1/add\'l. Intensity',
    'Strength': '3, +1/add\'l. Intensity',
    'Suggestion': '1/Intensity',
    'Summon Insects': '1/Intensity',
    'Tongues': '1/Intensity',
    'Tongues (Confuse Tongues)': '1/Intensity',
    'Confuse Tongues': '1/Intensity',
    'Tree': '1/Intensity',
    'Trip': '1/Intensity',
    'Unlock': '1/Intensity',
    'Unlock (Lock)': '1/Intensity',
    'Lock': '1/Intensity',
    'Vampiric Touch': '3',
    'Warp Wood': '1/Intensity',
    'Warp Wood (Straighten Wood)': '1/Intensity',
    'Straighten Wood': '1/Intensity',
    'Water Walk': '3, +1/add\'l. Intensity',
    'Web': '3, +1/add\'l. Intensity'
  },

  // Rank 3 Spells
  rank3: {
    'Aerial Servant': '3/Intensity',
    'Air Walk': '3, +1/add\'l. Intensity',
    'Animal Growth': '3, +1/add\'l. Intensity',
    'Animal Growth (Shrink Animal)': '3, +1/add\'l. Intensity',
    'Shrink Animal': '3, +1/add\'l. Intensity',
    'Animal Summoning I': '1/Intensity',
    'Animate Dead': '3, +1/add\'l. Intensity (+1 EXP)',
    'Anti-Plant Shell': '3, +1/add\'l. Intensity',
    'Atonement': '3, plus see description',
    'Big Interposing Hand': '3, +1/add\'l. Intensity',
    'Call Woodland Beings': '3, +1/add\'l. Intensity',
    'Charm Monster': '3/Intensity',
    'Cloud Kill': '3, +1/add\'l. Intensity',
    'Cloudkill': '3, +1/add\'l. Intensity',
    'Commune': '3, +1/add\'l. Intensity, +1 EXP',
    'Cone of Cold': '3, +1/add\'l. Intensity',
    'Confusion': '3, +1/add\'l. Intensity',
    'Conjure Elemental': '3, +1/add\'l. Intensity',
    'Control Temperature 10\' Radius': '3, +1/add\'l. Intensity',
    'Control Winds': '1/Intensity',
    'Cure Major Wounds': '3, +1/add\'l. Intensity',
    'Cure Major Wounds (Cause Major Wounds)': '3, +1/add\'l. Intensity',
    'Cause Major Wounds': '3, +1/add\'l. Intensity',
    'Detect Lie': '1/Intensity',
    'Detect Lie (Undetectable Lie)': '1/Intensity',
    'Undetectable Lie': '1/Intensity',
    'Dimension Door': '3, +1/add\'l. Intensity',
    'Dispel Evil': '3, +1/add\'l. Intensity',
    'Dispel Evil (Banish Good)': '3, +1/add\'l. Intensity',
    'Banish Good': '3, +1/add\'l. Intensity',
    'Divination': '3, +1/add\'l. Intensity',
    'Domination': '3/Intensity',
    'Enchant Weapon': '3, +1/add\'l. Intensity',
    'Exorcism': '3, +1/add\'l. Intensity',
    'Fear': '3, +1/add\'l. Intensity',
    'Feeblemind': '3, +1/add\'l. Intensity',
    'Free Action': '3, +1/add\'l. Intensity',
    'Fumble': '3, +1/add\'l. Intensity',
    'Hallucinatory Forest': '3/Intensity',
    'Hail/Ice Storm': '3, +1/add\'l. Intensity',
    'Ice Storm': '3, +1/add\'l. Intensity',
    'Heat/Cold Shield': '3, +1/add\'l. Intensity',
    'Hold Plant': '3, +1/add\'l. Intensity',
    'Hold Monster': '3, +1/add\'l. Intensity',
    'Illusionary Terrain': '3, +1/add\'l. Intensity',
    'Illusion, Advanced': '3, +1/add\'l. Intensity',
    'Advanced Illusion': '3, +1/add\'l. Intensity',
    'Insect Plague': '3, +1/add\'l. Intensity',
    'Invisibility, Greater': '3, +1/add\'l. Intensity',
    'Greater Invisibility': '3, +1/add\'l. Intensity',
    'Legend Lore': '3, +1/hour',
    'Leonard\'s Secure Cottage': '3, +1/add\'l. Intensity',
    'Lesser Creation': '3, +1/add\'l. Intensity',
    'Lower Water': '3, +1/add\'l. Intensity',
    'Lower Water (Raise Water)': '3, +1/add\'l. Intensity',
    'Raise Water': '3, +1/add\'l. Intensity',
    'Monster Summoning': '3, +1/add\'l. Intensity',
    'Neutralize Poison': '3, +1/add\'l. Intensity',
    'Neutralize Poison (Inflict Poison)': '3, +1/add\'l. Intensity',
    'Inflict Poison': '3, +1/add\'l. Intensity',
    'Pass Wall': '3, +1/add\'l. Intensity',
    'Passwall': '3, +1/add\'l. Intensity',
    'Phantasmal Terror': '3, +1/add\'l. Intensity',
    'Plane Shift': '3, +1/add\'l. Intensity',
    'Plant Door': '3, +1/add\'l. Intensity',
    'Polymorph Other': '3/Intensity',
    'Polymorph Self': '3, +1/add\'l. Intensity',
    'Power Word – Stun': '3, +1/add\'l. Intensity',
    'Power Word Stun': '3, +1/add\'l. Intensity',
    'Prayer': '3, +1/add\'l. Intensity',
    'Produce Fire': '3, +1/add\'l. Intensity',
    'Produce Fire (Quench Fire)': '3, +1/add\'l. Intensity',
    'Quench Fire': '3, +1/add\'l. Intensity',
    'Protection from Lightning': '3, +1/add\'l. Intensity',
    'Quest': '3, +1 EXP',
    'Raise Dead': '3, +1/add\'l. Intensity, +1 EXP',
    'Raise Dead (Slay Living)': '3, +1/add\'l. Intensity, +1 EXP',
    'Slay Living': '3, +1/add\'l. Intensity, +1 EXP',
    'Regenerate': '3/Intensity',
    'Regenerate (Wither)': '3/Intensity',
    'Wither': '3/Intensity',
    'Repel Insects': '3, +1/add\'l. Intensity',
    'Restoration': '3, +1/add\'l. Intensity',
    'Rock to Mud': '3, +1/add\'l. Intensity',
    'Rock to Mud (Mud to Rock)': '3, +1/add\'l. Intensity',
    'Mud to Rock': '3, +1/add\'l. Intensity',
    'Shadow Door': '3, +1/add\'l. Intensity',
    'Shadow Magic': 'See description',
    'Shadow Monsters': '3, +1/add\'l. Intensity',
    'Stone Shape': '1/Intensity',
    'Speak with Plants': '1/Intensity',
    'Sphere of Invulnerability, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Sphere of Invulnerability': '3, +1/add\'l. Intensity',
    'Sticks to Snakes': '3, +1/add\'l. Intensity',
    'Sticks to Snakes (Snakes to Sticks)': '3, +1/add\'l. Intensity',
    'Snakes to Sticks': '3, +1/add\'l. Intensity',
    'Stone Tell': '3',
    'Summon Shadow': '3/Intensity',
    'Telekinesis': '3, +1/add\'l. Intensity',
    'Teleport': '3, +1/add\'l. Intensity',
    'True Sight': '3, +1/add\'l. Intensity',
    'True Sight (False Sight)': '3, +1/add\'l. Intensity',
    'False Sight': '3, +1/add\'l. Intensity',
    'Wall of Fire': '3, +1/add\'l. Intensity',
    'Wall of Force': '3, +1/add\'l. Intensity',
    'Wall of Ice': '3, +1/add\'l. Intensity',
    'Wizard Sight': '1/Intensity'
  },

  // Rank 4 Spells
  rank4: {
    'Animal Summoning II': '3, +1/add\'l. Intensity',
    'Animate Object': '1/Intensity',
    'Anti-Animal Shell': '3, +1/add\'l. Intensity',
    'Anti-Magic Shell': '3, +1/add\'l. Intensity',
    'Antimagic Shell': '3, +1/add\'l. Intensity',
    'Big Grasping Hand': '3, +1/add\'l. Intensity',
    'Blade Barrier': '3, +1/add\'l. Intensity',
    'Chain Lightning': '3, +1/add\'l. Intensity',
    'Conjure Animals': '3, +1/add\'l. Intensity',
    'Conjure Fire Elemental': '3, +1/add\'l. Intensity',
    'Conjure Fire Elemental (Dismiss Fire Elemental)': '3, +1/add\'l. Intensity',
    'Dismiss Fire Elemental': '3, +1/add\'l. Intensity',
    'Control Undead': '3/Intensity',
    'Control Weather': '3/Intensity',
    'Death Spell': '3, +1/add\'l. Intensity',
    'Demi-Shadow Magic': '3, +1/add\'l. Intensity',
    'Demi-Shadow Monsters': '3, +1/add\'l. Intensity',
    'Disintegrate': '3/Intensity, +1 EXP',
    'Duo-Dimension': '3, +1/add\'l. Intensity',
    'Enchant Item': '3, +See description',
    'Etherealness, Lesser': '3, +1/add\'l. Intensity',
    'Lesser Etherealness': '3, +1/add\'l. Intensity',
    'Find the Path': '3, +1/add\'l. Intensity',
    'Find the Path (Lose the Path)': '3, +1/add\'l. Intensity',
    'Lose the Path': '3, +1/add\'l. Intensity',
    'Fireball, Delayed': '3, +1/add\'l. Intensity',
    'Delayed Fireball': '3, +1/add\'l. Intensity',
    'Flame Seeds': '3, +1/add\'l. Intensity',
    'Flesh to Stone': '3/Intensity',
    'Flesh to Stone (Stone to Flesh)': '3/Intensity',
    'Stone to Flesh': '3/Intensity',
    'Forbiddance': '3, +1/add\'l. Intensity',
    'Geas': '3, +1 EXP',
    'Heal': '3, +1/add\'l. Intensity',
    'Heal (Harm)': '3, +1/add\'l. Intensity',
    'Harm': '3, +1/add\'l. Intensity',
    'Heroes Feast': '3, +1/add\'l. Intensity',
    'Heroes\' Feast': '3, +1/add\'l. Intensity',
    'Illusion, Permanent': '3, +1/add\'l. Intensity',
    'Permanent Illusion': '3, +1/add\'l. Intensity',
    'Invisible Stalker': '3, +1 EXP, plus see description',
    'Live Oak': '3, +1/add\'l. Intensity',
    'Major Creation': '3, +1/add\'l. Intensity',
    'Monster Summoning, Greater': '3, +1/add\'l. Intensity',
    'Greater Monster Summoning': '3, +1/add\'l. Intensity',
    'Pass Plant': '3, +1/add\'l. Intensity',
    'Phase Door': '3, +1/add\'l. Intensity',
    'Power Word – Blind': '3, +1/add\'l. Intensity',
    'Power Word Blind': '3, +1/add\'l. Intensity',
    'Prismatic Spray': '3',
    'Prismatic Wall': '3/Intensity',
    'Project Image': '3, +1/add\'l. Intensity',
    'Reincarnation': '3, +1/add\'l. Intensity, +1 EXP',
    'Shadow Walk': '3, +1/add\'l. Intensity',
    'Speak with Monsters': '3, +1/add\'l. Intensity',
    'Sphere of Invulnerability, Greater': '3, +1/add\'l. Intensity',
    'Greater Sphere of Invulnerability': '3, +1/add\'l. Intensity',
    'Teleport, Precise': '3, +1/add\'l. Intensity',
    'Precise Teleport': '3, +1/add\'l. Intensity',
    'Turn Wood': '3, +1/add\'l. Intensity',
    'Wall of Stone': '3, +1/add\'l. Intensity',
    'Wall of Thorns': '3, +1/add\'l. Intensity',
    'Water to Dust': '3, +1/add\'l. Intensity',
    'Water to Dust (Dust to Water)': '3, +1/add\'l. Intensity',
    'Dust to Water': '3, +1/add\'l. Intensity',
    'Weather Summoning': '3',
    'Wish, Limited': '3, +1 or more EXP',
    'Limited Wish': '3, +1 or more EXP',
    'Word of Recall': '3, +1/add\'l. Intensity'
  },

  // Rank 5 Spells
  rank5: {
    'Alter Reality': '3, +1 or more EXP',
    'Antipathy/Sympathy': '3, +1/add\'l. Intensity',
    'Antipathy': '3, +1/add\'l. Intensity',
    'Sympathy': '3, +1/add\'l. Intensity',
    'Astral Spell': '3, +1/add\'l. Intensity',
    'Big Crushing Fist': '3, +1/add\'l. Intensity',
    'Changestaff': '3, +1 EXP',
    'Conjure Earth Elemental': '3, +1/add\'l. Intensity',
    'Conjure Earth Elemental (Dismiss Earth Elemental)': '3, +1/add\'l. Intensity',
    'Dismiss Earth Elemental': '3, +1/add\'l. Intensity',
    'Creeping Doom': '3, +1/add\'l. Intensity',
    'Disjunction': '3, +1/add\'l. Intensity, +1 EXP',
    'Earthquake': '3, +1/add\'l. Intensity',
    'Energy Drain': '3',
    'Etherealness, Greater': '3, +1/add\'l. Intensity',
    'Greater Etherealness': '3, +1/add\'l. Intensity',
    'Exaction': '3, +1 EXP',
    'Finger of Death': '3, +1/add\'l. Intensity, +3 EXP',
    'Fire Storm': '3, +1/add\'l. Intensity',
    'Fire Storm (Greater Quench Fire)': '3, +1/add\'l. Intensity',
    'Greater Quench Fire': '3, +1/add\'l. Intensity',
    'Gate': '3/Intensity, + See description',
    'Holy Word': '3, +1 EXP',
    'Holy Word (Unholy Word)': '3, +1 EXP',
    'Unholy Word': '3, +1 EXP',
    'Irresistible Dance': '3',
    'Mass Charm': '3/Intensity, +1 EXP',
    'Maze': '3, +1/add\'l. Intensity',
    'Metal to Wood': '3, +1/add\'l. Intensity, +1 EXP',
    'Meteor Shower': '3/Intensity',
    'Monster Summoning, Ultimate': '3, +1/add\'l. Intensity',
    'Ultimate Monster Summoning': '3, +1/add\'l. Intensity',
    'Part Water': '3, +1/add\'l. Intensity',
    'Permanency': '3, +1 EXP',
    'Polymorph any Object': '3/Intensity',
    'Power Word – Kill': '3/Intensity, +1 EXP',
    'Power Word Kill': '3/Intensity, +1 EXP',
    'Prismatic Sphere': '3/Intensity',
    'Resurrection': '3, +1/add\'l. Intensity, +2 EXP',
    'Resurrection (Destruction)': '3, +1/add\'l. Intensity, +2 EXP',
    'Destruction': '3, +1/add\'l. Intensity, +2 EXP',
    'Succor': '3, +1 EXP',
    'Sun Ray': '3/Intensity',
    'Symbol': '3, (Death +2 EXP)',
    'Time Stop': '3/Intensity, +1 EXP',
    'Transport via Plants': '3',
    'Trap the Soul': '3, +1 EXP',
    'Wind Walk': '3, +1/add\'l. Intensity',
    'Wish': '3, +1 or more EXP'
  },

  /**
   * Get the cost for a spell by name
   * Searches all ranks and returns the cost if found
   */
  getSpellCost(spellName, rank = null) {
    if (!spellName) return null;
    
    const normalizedName = spellName.trim();
    
    // If rank specified, search only that rank
    if (rank !== null) {
      const rankKey = rank === 0 ? 'cantrips' : `rank${rank}`;
      const rankData = this[rankKey];
      if (rankData) {
        // Try exact match first
        if (rankData[normalizedName]) {
          return rankData[normalizedName];
        }
        // Try case-insensitive match
        for (const [name, cost] of Object.entries(rankData)) {
          if (name.toLowerCase() === normalizedName.toLowerCase()) {
            return cost;
          }
        }
      }
      return null;
    }
    
    // Search all ranks
    const allRanks = ['cantrips', 'rank1', 'rank2', 'rank3', 'rank4', 'rank5'];
    for (const rankKey of allRanks) {
      const rankData = this[rankKey];
      // Try exact match first
      if (rankData[normalizedName]) {
        return rankData[normalizedName];
      }
      // Try case-insensitive match
      for (const [name, cost] of Object.entries(rankData)) {
        if (name.toLowerCase() === normalizedName.toLowerCase()) {
          return cost;
        }
      }
    }
    
    return null;
  },

  /**
   * Get rank number from rank key (for internal use)
   */
  getRankFromKey(rankKey) {
    if (rankKey === 'cantrips') return 0;
    const match = rankKey.match(/rank(\d)/);
    return match ? parseInt(match[1], 10) : null;
  }
};

// Make available globally
window.SpellData = SpellData;
