/* ============================================
   MYTHRAS CLASSIC FANTASY CHARACTER SHEET
   Spell Data by Rank
   ============================================ */

const SPELL_DATA = {
  cantrips: [
    { name: "Appraise", cost: "1" },
    { name: "Avert", cost: "1" },
    { name: "Babble", cost: "1" },
    { name: "Beastcall", cost: "1" },
    { name: "Befuddle", cost: "1" },
    { name: "Calculate", cost: "1" },
    { name: "Calm", cost: "1" },
    { name: "Calm Animal", cost: "1" },
    { name: "Chill/Heat", cost: "1" },
    { name: "Cleanse/Dishevel", cost: "1" },
    { name: "Coordination", cost: "1" },
    { name: "Deflect", cost: "1" },
    { name: "Dry", cost: "1" },
    { name: "Fanaticism/Demoralize", cost: "1" },
    { name: "Frostbite", cost: "1" },
    { name: "Glamour/Repugnance", cost: "1" },
    { name: "Glue", cost: "1" },
    { name: "Ignite/Extinguish", cost: "1" },
    { name: "Incognito", cost: "1" },
    { name: "Ironhand", cost: "1" },
    { name: "Magic Tricks", cost: "1" },
    { name: "Magnify", cost: "1" },
    { name: "Might", cost: "1" },
    { name: "Mimic", cost: "1" },
    { name: "Mobility", cost: "1" },
    { name: "Perfume", cost: "1" },
    { name: "Pet", cost: "1" },
    { name: "Polish", cost: "1" },
    { name: "Preserve", cost: "1" },
    { name: "Protection", cost: "1" },
    { name: "Repair", cost: "1" },
    { name: "Spiritshield", cost: "1" },
    { name: "Tidy", cost: "1" },
    { name: "Tune", cost: "1" },
    { name: "Voice", cost: "1" }
  ],
  
  rank1: [
    { name: "Acid Arrow", cost: "1/Int." },
    { name: "Affect Normal Fires", cost: "1/Int." },
    { name: "Alarm", cost: "1/Int." },
    { name: "Animal Friendship", cost: "1/Int." },
    { name: "Armor", cost: "3, +1/Int." },
    { name: "Audible Illusion", cost: "1/Int." },
    { name: "Barkskin", cost: "1/Int." },
    { name: "Bind", cost: "1/Int." },
    { name: "Bless/Curse", cost: "1/Int." },
    { name: "Blindness", cost: "3, +1/Int." },
    { name: "Blur", cost: "3, +1/Int." },
    { name: "Ceremony", cost: "1" },
    { name: "Change Appearance", cost: "1/Int." },
    { name: "Charm Being", cost: "3/Int." },
    { name: "Chill Touch", cost: "1/Int." },
    { name: "Color Cascade", cost: "1/Int." },
    { name: "Combine", cost: "1" },
    { name: "Command", cost: "3" },
    { name: "Create Water/Destroy Water", cost: "1/Int." },
    { name: "Cure Fatigue/Cause Fatigue", cost: "1" },
    { name: "Cure Minor Wounds/Cause Minor Wounds", cost: "3" },
    { name: "Deafness", cost: "3, +1/Int." },
    { name: "Detect Charm/Hide Charm", cost: "1/Int." },
    { name: "Detect Evil/Detect Good", cost: "1/Int." },
    { name: "Detect Illusion", cost: "1/Int." },
    { name: "Detect Magic", cost: "1/Int." },
    { name: "Detect Poison", cost: "1/Int." },
    { name: "Detect Snares and Pits", cost: "1/Int." },
    { name: "Detect Undead", cost: "1/Int." },
    { name: "Disk of Burden", cost: "1/Int." },
    { name: "Dust Devil", cost: "3, +1/Int." },
    { name: "Endure Heat/Cold", cost: "1/Int." },
    { name: "Enlarge/Reduce", cost: "3, +1/Int." },
    { name: "Entangle", cost: "3, +1/Int." },
    { name: "Erase Writing", cost: "1/Int." },
    { name: "Faerie Fire", cost: "3, +1/Int." },
    { name: "Faerie Lights", cost: "1/Int." },
    { name: "Familiar", cost: "3/Int., +1 EXP" },
    { name: "Feather Fall", cost: "1/Int." },
    { name: "Find Traps", cost: "3, +1/Int." },
    { name: "Flame Blade", cost: "1/Int." },
    { name: "Flaming Hands", cost: "1/Int." },
    { name: "Friendship", cost: "3, +1/Int." },
    { name: "Goodberry/Badberry", cost: "1/Int." },
    { name: "Grease", cost: "1/Int." },
    { name: "Hypnotism", cost: "1/Int." },
    { name: "Identify", cost: "1/Int." },
    { name: "Illusion, Lesser", cost: "1/Int." },
    { name: "Invisibility, Lesser", cost: "3, +1/Int." },
    { name: "Invisibility to Animals", cost: "3, +1/Int." },
    { name: "Invisibility to Undead", cost: "3" },
    { name: "Jump", cost: "1/Int." },
    { name: "Know Languages/Confuse Languages", cost: "1/Int." },
    { name: "Leonard's False Trap", cost: "1" },
    { name: "Levitate", cost: "1/Int." },
    { name: "Light", cost: "1/Int." },
    { name: "Light/Darkness", cost: "1/Int." },
    { name: "Locate Animals or Plants", cost: "1/Int." },
    { name: "Magic Aura", cost: "1/Int." },
    { name: "Magic Missile", cost: "3, +1/Int." },
    { name: "Magical Stone", cost: "1/Int." },
    { name: "Message", cost: "1/Int." },
    { name: "Messenger", cost: "1/Int." },
    { name: "Misdirection", cost: "3" },
    { name: "Pass Without Trace", cost: "1/Int." },
    { name: "Predict Weather", cost: "1/Int." },
    { name: "Protection from Cantrips", cost: "1/Int." },
    { name: "Protection from Evil/Protection from Good", cost: "1/Int." },
    { name: "Purify Food and Drink/Contaminate Food and Drink", cost: "1/Int." },
    { name: "Read Magic", cost: "1/Int." },
    { name: "Reflect Gaze", cost: "1/Int." },
    { name: "Remove Fear/Cause Fear", cost: "1/Int." },
    { name: "Sanctuary", cost: "1/Int." },
    { name: "Secure Portal", cost: "1/Int." },
    { name: "Shield", cost: "3, +1/Int." },
    { name: "Shillelagh", cost: "1/Int." },
    { name: "Shocking Touch", cost: "1/Int." },
    { name: "Silence", cost: "3, +1/Int." },
    { name: "Sleep", cost: "3, +1/Int." },
    { name: "Slow Poison", cost: "3, +1/Int." },
    { name: "Spider Climb", cost: "1/Int." },
    { name: "Uncontrollable Horrible Laughter", cost: "1/Int." },
    { name: "Unseen Servant", cost: "1/Int." },
    { name: "Ventriloquism", cost: "1/Int." }
  ],
  
  rank2: [
    { name: "Aid", cost: "3, +1/Int." },
    { name: "Alter Self", cost: "3, +1/Int." },
    { name: "Augury", cost: "1/Int." },
    { name: "Blink", cost: "3, +1/Int." },
    { name: "Breathe Water/Breathe Air", cost: "3, +1/Int." },
    { name: "Call Lightning", cost: "3, +1/Int." },
    { name: "Chant", cost: "3, +1/Int." },
    { name: "Charm Being or Mammal", cost: "3/Int." },
    { name: "Clairaudience/Clairvoyance", cost: "See desc." },
    { name: "Commune with Nature", cost: "3, +1/Int." },
    { name: "Continual Light/Continual Darkness", cost: "3" },
    { name: "Create Food and Water", cost: "3, +1/Int." },
    { name: "Cure Blindness or Deafness/Cause Blindness or Deafness", cost: "3" },
    { name: "Cure Disease/Cause Disease", cost: "1/Int." },
    { name: "Cure Serious Wounds/Cause Serious Wounds", cost: "3" },
    { name: "Darkness", cost: "1/Int." },
    { name: "Darkvision", cost: "1/Int." },
    { name: "Detect Evil", cost: "1/Int." },
    { name: "Detect Invisibility", cost: "1/Int." },
    { name: "Dispel Magic", cost: "1/Int." },
    { name: "Enfeeblement", cost: "3, +1/Int." },
    { name: "Feign Death", cost: "3, +1/Int." },
    { name: "Fireball", cost: "3, +1/Int." },
    { name: "Fire Trap", cost: "3, +1/Int." },
    { name: "Flame Arrow", cost: "3, +1/Int." },
    { name: "Flame Strike", cost: "3, +1/Int." },
    { name: "Flame Walk", cost: "3, +1/Int." },
    { name: "Fly", cost: "3, +1/Int." },
    { name: "Forget", cost: "1/Int." },
    { name: "Gust of Wind", cost: "3, +1/Int." },
    { name: "Haste", cost: "3, +1/Int." },
    { name: "Heat Metal/Chill Metal", cost: "3, +1/Int." },
    { name: "Hold Animal", cost: "3, +1/Int." },
    { name: "Hold Person", cost: "3, +1/Int." },
    { name: "Hold Undead", cost: "3, +1/Int." },
    { name: "Illusion, Greater", cost: "1/Int." },
    { name: "Invisibility 10ft", cost: "3, +1/Int." },
    { name: "Know Passions/Obscure Passions", cost: "1/Int." },
    { name: "Leonard's Tiny Magic Hut", cost: "3, +1/Int." },
    { name: "Lightning Bolt", cost: "3, +1/Int." },
    { name: "Locate Object/Obscure Object", cost: "1/Int." },
    { name: "Mage Lock", cost: "3, +1/Int." },
    { name: "Magic Mouth", cost: "1/Int." },
    { name: "Minute Meteors", cost: "3, +1/Int." },
    { name: "Mirror Images", cost: "1/Int." },
    { name: "Monster Summoning, Lesser", cost: "3, +1/Int." },
    { name: "Obscurement", cost: "1/Int." },
    { name: "Plant Growth", cost: "1/Int." },
    { name: "Produce Flame", cost: "3, +1/Int." },
    { name: "Protection from Cold", cost: "3, +1/Int." },
    { name: "Protection from Evil 10' Radius/Protection from Good 10' Radius", cost: "3, +1/Int." },
    { name: "Protection from Fire", cost: "3, +1/Int." },
    { name: "Protection from Mundane Missiles", cost: "3, +1/Int." },
    { name: "Pyrotechnics", cost: "3, +1/Int." },
    { name: "Read Thoughts", cost: "1/Int." },
    { name: "Remove Curse/Bestow Curse", cost: "3, +1/Int." },
    { name: "Remove Paralysis", cost: "3, +1/Int." },
    { name: "Scare", cost: "3, +1/Int." },
    { name: "Sigil of Warding", cost: "1/Int." },
    { name: "Slow", cost: "3/Int." },
    { name: "Snake Charm", cost: "1/Int." },
    { name: "Snare", cost: "3" },
    { name: "Speak with Animals", cost: "1/Int." },
    { name: "Speak with Dead", cost: "1/Int." },
    { name: "Spectral Hand", cost: "1/Int." },
    { name: "Spiritual Hammer", cost: "3, +1/Int." },
    { name: "Stinking Cloud", cost: "3, +1/Int." },
    { name: "Strength", cost: "3, +1/Int." },
    { name: "Suggestion", cost: "1/Int." },
    { name: "Summon Insects", cost: "1/Int." },
    { name: "Tongues/Confuse Tongues", cost: "1/Int." },
    { name: "Tree", cost: "1/Int." },
    { name: "Trip", cost: "1/Int." },
    { name: "Unlock/Lock", cost: "1/Int." },
    { name: "Vampiric Touch", cost: "3" },
    { name: "Warp Wood/Straighten Wood", cost: "1/Int." },
    { name: "Water Walk", cost: "3, +1/Int." },
    { name: "Web", cost: "3, +1/Int." }
  ],
  
  rank3: [
    { name: "Aerial Servant", cost: "3/Int." },
    { name: "Air Walk", cost: "3, +1/Int." },
    { name: "Animal Growth/Shrink Animal", cost: "3, +1/Int." },
    { name: "Animal Summoning I", cost: "1/Int." },
    { name: "Animate Dead", cost: "3, +1/Int. (+1 EXP)" },
    { name: "Anti-Plant Shell", cost: "3, +1/Int." },
    { name: "Atonement", cost: "3, +see desc." },
    { name: "Big Interposing Hand", cost: "3, +1/Int." },
    { name: "Call Woodland Beings", cost: "3, +1/Int." },
    { name: "Charm Monster", cost: "3/Int." },
    { name: "Cloud Kill", cost: "3, +1/Int." },
    { name: "Commune", cost: "3, +1/Int., +1 EXP" },
    { name: "Cone of Cold", cost: "3, +1/Int." },
    { name: "Confusion", cost: "3, +1/Int." },
    { name: "Conjure Elemental", cost: "3, +1/Int." },
    { name: "Control Temperature 10' Radius", cost: "3, +1/Int." },
    { name: "Control Winds", cost: "1/Int." },
    { name: "Cure Major Wounds/Cause Major Wounds", cost: "3, +1/Int." },
    { name: "Detect Lie/Undetectable Lie", cost: "1/Int." },
    { name: "Dimension Door", cost: "3, +1/Int." },
    { name: "Dispel Evil/Banish Good", cost: "3, +1/Int." },
    { name: "Divination", cost: "3, +1/Int." },
    { name: "Domination", cost: "3/Int." },
    { name: "Enchant Weapon", cost: "3, +1/Int." },
    { name: "Exorcism", cost: "3, +1/Int." },
    { name: "Fear", cost: "3, +1/Int." },
    { name: "Feeblemind", cost: "3, +1/Int." },
    { name: "Free Action", cost: "3, +1/Int." },
    { name: "Fumble", cost: "3, +1/Int." },
    { name: "Hail/Ice Storm", cost: "3, +1/Int." },
    { name: "Hallucinatory Forest", cost: "3/Int." },
    { name: "Heat/Cold Shield", cost: "3, +1/Int." },
    { name: "Hold Monster", cost: "3, +1/Int." },
    { name: "Hold Plant", cost: "3, +1/Int." },
    { name: "Illusion, Advanced", cost: "3, +1/Int." },
    { name: "Illusionary Terrain", cost: "3, +1/Int." },
    { name: "Insect Plague", cost: "3, +1/Int." },
    { name: "Invisibility, Greater", cost: "3, +1/Int." },
    { name: "Legend Lore", cost: "3, +1/hour" },
    { name: "Leonard's Secure Cottage", cost: "3, +1/Int." },
    { name: "Lesser Creation", cost: "3, +1/Int." },
    { name: "Lower Water/Raise Water", cost: "3, +1/Int." },
    { name: "Monster Summoning", cost: "3, +1/Int." },
    { name: "Neutralize Poison/Inflict Poison", cost: "3, +1/Int." },
    { name: "Pass Wall", cost: "3, +1/Int." },
    { name: "Phantasmal Terror", cost: "3, +1/Int." },
    { name: "Plane Shift", cost: "3, +1/Int." },
    { name: "Plant Door", cost: "3, +1/Int." },
    { name: "Polymorph Other", cost: "3/Int." },
    { name: "Polymorph Self", cost: "3, +1/Int." },
    { name: "Power Word - Stun", cost: "3, +1/Int." },
    { name: "Prayer", cost: "3, +1/Int." },
    { name: "Produce Fire/Quench Fire", cost: "3, +1/Int." },
    { name: "Protection from Lightning", cost: "3, +1/Int." },
    { name: "Quest", cost: "3, +1 EXP" },
    { name: "Raise Dead/Slay Living", cost: "3, +1/Int., +1 EXP" },
    { name: "Regenerate/Wither", cost: "3/Int." },
    { name: "Repel Insects", cost: "3, +1/Int." },
    { name: "Restoration", cost: "3, +1/Int." },
    { name: "Rock to Mud/Mud to Rock", cost: "3, +1/Int." },
    { name: "Shadow Door", cost: "3, +1/Int." },
    { name: "Shadow Magic", cost: "See desc." },
    { name: "Shadow Monsters", cost: "3, +1/Int." },
    { name: "Speak with Plants", cost: "1/Int." },
    { name: "Sphere of Invulnerability, Lesser", cost: "3, +1/Int." },
    { name: "Sticks to Snakes/Snakes to Sticks", cost: "3, +1/Int." },
    { name: "Stone Shape", cost: "1/Int." },
    { name: "Stone Tell", cost: "3" },
    { name: "Summon Shadow", cost: "3/Int." },
    { name: "Telekinesis", cost: "3, +1/Int." },
    { name: "Teleport", cost: "3, +1/Int." },
    { name: "True Sight/False Sight", cost: "3, +1/Int." },
    { name: "Wall of Fire", cost: "3, +1/Int." },
    { name: "Wall of Force", cost: "3, +1/Int." },
    { name: "Wall of Ice", cost: "3, +1/Int." },
    { name: "Wizard Sight", cost: "1/Int." }
  ],
  
  rank4: [
    { name: "Animal Summoning II", cost: "3, +1/Int." },
    { name: "Animate Object", cost: "1/Int." },
    { name: "Anti-Animal Shell", cost: "3, +1/Int." },
    { name: "Anti-Magic Shell", cost: "3, +1/Int." },
    { name: "Big Grasping Hand", cost: "3, +1/Int." },
    { name: "Blade Barrier", cost: "3, +1/Int." },
    { name: "Chain Lightning", cost: "3, +1/Int." },
    { name: "Conjure Animals", cost: "3, +1/Int." },
    { name: "Conjure Fire Elemental/Dismiss Fire Elemental", cost: "3, +1/Int." },
    { name: "Control Undead", cost: "3/Int." },
    { name: "Control Weather", cost: "3/Int." },
    { name: "Death Spell", cost: "3, +1/Int." },
    { name: "Demi-Shadow Magic", cost: "3, +1/Int." },
    { name: "Demi-Shadow Monsters", cost: "3, +1/Int." },
    { name: "Disintegrate", cost: "3/Int., +1 EXP" },
    { name: "Duo-Dimension", cost: "3, +1/Int." },
    { name: "Enchant Item", cost: "3, +see desc." },
    { name: "Etherealness, Lesser", cost: "3, +1/Int." },
    { name: "Find the Path/Lose the Path", cost: "3, +1/Int." },
    { name: "Fireball, Delayed", cost: "3, +1/Int." },
    { name: "Flame Seeds", cost: "3, +1/Int." },
    { name: "Flesh to Stone/Stone to Flesh", cost: "3/Int." },
    { name: "Forbiddance", cost: "3, +1/Int." },
    { name: "Geas", cost: "3, +1 EXP" },
    { name: "Heal/Harm", cost: "3, +1/Int." },
    { name: "Heroes Feast", cost: "3, +1/Int." },
    { name: "Illusion, Permanent", cost: "3, +1/Int." },
    { name: "Invisible Stalker", cost: "3, +1 EXP, +see desc." },
    { name: "Live Oak", cost: "3, +1/Int." },
    { name: "Major Creation", cost: "3, +1/Int." },
    { name: "Monster Summoning, Greater", cost: "3, +1/Int." },
    { name: "Pass Plant", cost: "3, +1/Int." },
    { name: "Phase Door", cost: "3, +1/Int." },
    { name: "Power Word - Blind", cost: "3, +1/Int." },
    { name: "Prismatic Spray", cost: "3" },
    { name: "Prismatic Wall", cost: "3/Int." },
    { name: "Project Image", cost: "3, +1/Int." },
    { name: "Reincarnation", cost: "3, +1/Int., +1 EXP" },
    { name: "Shadow Walk", cost: "3, +1/Int." },
    { name: "Speak with Monsters", cost: "3, +1/Int." },
    { name: "Sphere of Invulnerability, Greater", cost: "3, +1/Int." },
    { name: "Teleport, Precise", cost: "3, +1/Int." },
    { name: "Turn Wood", cost: "3, +1/Int." },
    { name: "Wall of Stone", cost: "3, +1/Int." },
    { name: "Wall of Thorns", cost: "3, +1/Int." },
    { name: "Water to Dust/Dust to Water", cost: "3, +1/Int." },
    { name: "Weather Summoning", cost: "3" },
    { name: "Wish, Limited", cost: "3, +1 or more EXP" },
    { name: "Word of Recall", cost: "3, +1/Int." }
  ],
  
  rank5: [
    { name: "Alter Reality", cost: "3, +1 or more EXP" },
    { name: "Antipathy/Sympathy", cost: "3, +1/Int." },
    { name: "Astral Spell", cost: "3, +1/Int." },
    { name: "Big Crushing Fist", cost: "3, +1/Int." },
    { name: "Changestaff", cost: "3, +1 EXP" },
    { name: "Conjure Earth Elemental/Dismiss Earth Elemental", cost: "3, +1/Int." },
    { name: "Creeping Doom", cost: "3, +1/Int." },
    { name: "Disjunction", cost: "3, +1/Int., +1 EXP" },
    { name: "Earthquake", cost: "3, +1/Int." },
    { name: "Energy Drain", cost: "3" },
    { name: "Etherealness, Greater", cost: "3, +1/Int." },
    { name: "Exaction", cost: "3, +1 EXP" },
    { name: "Finger of Death", cost: "3, +1/Int., +3 EXP" },
    { name: "Fire Storm/Greater Quench Fire", cost: "3, +1/Int." },
    { name: "Gate", cost: "3/Int., +see desc." },
    { name: "Holy Word/Unholy Word", cost: "3, +1 EXP" },
    { name: "Irresistible Dance", cost: "3" },
    { name: "Mass Charm", cost: "3/Int., +1 EXP" },
    { name: "Maze", cost: "3, +1/Int." },
    { name: "Metal to Wood", cost: "3, +1/Int., +1 EXP" },
    { name: "Meteor Shower", cost: "3/Int." },
    { name: "Monster Summoning, Ultimate", cost: "3, +1/Int." },
    { name: "Part Water", cost: "3, +1/Int." },
    { name: "Permanency", cost: "3, +1 EXP" },
    { name: "Polymorph any Object", cost: "3/Int." },
    { name: "Power Word - Kill", cost: "3/Int., +1 EXP" },
    { name: "Prismatic Sphere", cost: "3/Int." },
    { name: "Resurrection/Destruction", cost: "3, +1/Int., +2 EXP" },
    { name: "Succor", cost: "3, +1 EXP" },
    { name: "Sun Ray", cost: "3/Int." },
    { name: "Symbol", cost: "3, (+2 EXP for Death)" },
    { name: "Time Stop", cost: "3/Int., +1 EXP" },
    { name: "Transport via Plants", cost: "3" },
    { name: "Trap the Soul", cost: "3, +1 EXP" },
    { name: "Wind Walk", cost: "3, +1/Int." },
    { name: "Wish", cost: "3, +1 or more EXP" }
  ]
};

/**
 * Get spell cost by name and rank
 */
function getSpellCost(spellName, rank) {
  const spells = SPELL_DATA[rank];
  if (!spells) return null;
  
  const normalizedSearch = spellName.toLowerCase().trim();
  const spell = spells.find(s => s.name.toLowerCase() === normalizedSearch);
  return spell ? spell.cost : null;
}

/**
 * Find matching spells for autocomplete
 */
function findMatchingSpells(partial, rank) {
  const spells = SPELL_DATA[rank];
  if (!spells || !partial) return [];
  
  const normalizedPartial = partial.toLowerCase().trim();
  return spells.filter(s => s.name.toLowerCase().includes(normalizedPartial));
}

// Export for use in app.js
window.SpellData = {
  SPELL_DATA,
  getSpellCost,
  findMatchingSpells
};
